import type { EnemySpawn } from '../../../game/mapdef';
import { registerMaps } from '../../registry';

/**
 * The Tournament of Power stage in the Null Realm: three linked sections (A west ↔ B centre ↔ C east),
 * arena tiles over the void with jagged, crumbling edges. `ringOut` lets knocked-back enemies fall out.
 * Generic rival fighters appear from Ch14; a chapter can clear them for staged fights by setting `fc_topQuiet`.
 * Central open areas (keep these clear for boss fights): A (22,16), B (22,16), C west (12,15) / east (35,15).
 */

const TOP = 'chapter>=14&!fc_topQuiet';
const rival = (type: string, x: number, y: number): EnemySpawn => ({ type, x, y, showIf: TOP });

registerMaps([
  {
    id: 'top_arena_a', name: 'Tournament Stage - West Ring', music: 'tournament', hostile: true, ringOut: true,
    region: 'Tournament of Power', backdrop: '#0a0618',
    legend: { 'v': 'void', 'A': 'arena', 'k': 'rock', 'm': 'metal' },
    grid: [
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvAvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvAAAAAAvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvAAAAAAAvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvAvvvvvvvvvvAAvvAAvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvAAAAvvAAAvAAAAvvvvvvvAvvAAvv',
      'vvvAvAAAAAAvvvvAAAAAAvAAAAAAAAvvvvvvAAAAAAvv',
      'vvvAAAAAAAAvvAvAAAAAAAvAAAAAAAAAAAvAAAAAAAvv',
      'vvAAAAAAAAAAAAAAAAAAAAvAAAAAAkAAAAAAAAAAAkvv',
      'vAAAAAAAAAkAAAAAAAmmmmmvmmmAAAAAAAAAAAAAAAvv',
      'vAAAAAAAAAAAAAAAmmmmmAvvmmmmmAAAAAAAAAAAAmmm',
      'vAAAAAAAAAAAAAmmmmAAAAvAAAkmmmmAAAAAAAAAAmmm',
      'vAAAAAAAAAAAAmmmAAAAAAAAAAAAAmmmAAAAAAAAAmmm',
      'vAAAAAAAAAAAAmmAAAAAAAAAAAAAAAmmAAAAAAAAAmmm',
      'vAAAAAAAAAAAmmmAAAAAAAAAAAAAAAmmmAAAAAAAAmmm',
      'vAAAAAAAAAAAmmAAAAAAAAmAAAAAAAAmmAAAkAAAAmmm',
      'vAAAAAAAAAAAmmAAAAAAAmmmAAAAAAAmmAAAAAAAAmmm',
      'vAAAAAAkAAAAmmAAAAAAAAmAAAAAAAAmmAAAAkAAAmmm',
      'vAAAAAAAAAAAmmmAAAAAAAAAAAAAAAmmmAAAAAAAAmmm',
      'vAAAAAAAAAAAAmmAAAAAAAAAAAAAAAmmAAAAAAkkAmmm',
      'vAAAAAAAAAAAAmmmAAAAAAAAAAAAAmmmAAAAAAAAAmmm',
      'vAAAkAAAAAAAkAmmmmAAAAAAAAkmmmmAAAAAAAAAAmmm',
      'vAvAAAAAAkAkAkAAmmmmmAAAmmmmmAAAAAAAAAAAAAvv',
      'vvvAAAAAAAAAAAAAAAmmmmmmmmmAAAAAAAAkAAAAAAvv',
      'vvvAAAAAAAAAAAAAAAAAkAAAAAAAAAkAvAAkAAAAAAvv',
      'vvvvAAvvAAAAvvvvAAAAAAAAAAAvvvAvvAAAAAvvvvvv',
      'vvvvkAvvAAAAvvvvvvvvAAAAkAvvvvvvvAAAAAvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvAAkAAAvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvAAvvvvvAvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    ],
    props: [
      ['pillar', 3, 9], ['pillar', 38, 6.6], ['pillar', 4, 20], ['pillar', 36, 21],
      ['brokenPillar', 14, 8], ['brokenPillar', 30, 7], ['brokenPillar', 12, 23], ['brokenPillar', 24, 23.4],
      ['rubble', 9, 15], ['rubble', 34, 14], ['rubble', 31, 11.2], ['rubble', 19, 25.2], ['smallRock', 26, 9], ['smallRock', 7, 12],
      ['crater', 18, 19], ['crater', 23, 11.5],
    ],
    enemies: [rival('fc_topBrawler', 12, 12), rival('fc_topBrawler', 31, 19), rival('fc_topGunner', 35, 11)],
    objects: [
      { type: 'save', x: 3, y: 14 },
      { type: 'flight', x: 6, y: 8, to: 'top_arena_a', tx: 6, ty: 2, label: 'Floating rock' },
      { type: 'flight', x: 4, y: 3, to: 'top_arena_a', tx: 7, ty: 9, label: 'Stage' },
      { type: 'chest', x: 8, y: 3, id: 'fc_cap_topa_1', item: 'end3' },
      { type: 'breakable', x: 7, y: 18, size: 2 },
      { type: 'breakable', x: 37, y: 18, size: 1 },
      { type: 'breakable', x: 16, y: 23, size: 3 },
    ],
    exits: { east: { to: 'top_arena_b' } },
  },
  {
    id: 'top_arena_b', name: 'Tournament Stage - Central Ring', music: 'tournament', hostile: true, ringOut: true,
    region: 'Tournament of Power', backdrop: '#0a0618',
    legend: { 'v': 'void', 'A': 'arena', 'k': 'rock', 'm': 'metal' },
    grid: [
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvAAAAAvvvvvvvvvvAAAAAvvvv',
      'vvvvvvvvvvvvvvvvvvAAAAAAAAvvvvvvvvkAAAAAvvvv',
      'vvvvvvvvvvvvvvvvvvvAAAAAAAkvAAvvvvvvvvvvvvvv',
      'vvvvvvAvvvvvvvvvvAvvAAAAAAAvAAvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvAAmmmmmmmmmAAAAAAAAAvvvvAAvv',
      'vvAAAAvvvvvvvvAAAAAAAAAAAAAAAAAAAAAAAAvvAAvv',
      'vvAAAAvvvvvAAAAAAAmmmmmmmmmAAAAAAAAAAAAAAAvv',
      'vvAAAAAvvAAAAAAmmmmmmmmmmmmmmmAAAAAAAAAAAAvv',
      'mmmAAAAAAAAAAAmmmmmAAAAAAAmmmmmAAAAAAAAAAmmm',
      'mmmAAAAAAAAAmmmmAAAAAAAAAAAAAmmmmAAAAAAAAmmm',
      'mmmAAAAAAAAAmmmAAAAAAAAAAAAAAAmmmAAAAAAAAmmm',
      'mmmAAAAAAAAmmmAAAAAmmmAmmmAAAAAmmmAAAAAAAmmm',
      'mmmAAkAAAAmmmkAAAAmAAAAAAAmAAAAAmmmkAAAAAmmm',
      'mmmAAAAAAAmmmAAAAmAAAAAkAAAmAAAAmmmAAAAAAmmm',
      'mmmAAAAAAAmmmAAAAmAAAAAAAAAmAAAAmmmAAAAAAmmm',
      'mmmAkAAAAAmmmAAAAmAAAAAAAkAmAAAAmmmAAAAAAmmm',
      'mmmAAAAAAAmmmAAAAAmAAAAAAAmAAAAAmmmAAAAkAmmm',
      'mmmAAAAAAAAmmmAAAAAmmmAmmmAAAAAmmmAAAAAAAmmm',
      'mmmAAAAAAAAAmmmAAAAAAAAAAAAAAAmmmAAAAAAAAmmm',
      'mmmAAAAAAAAAmmmmAAAAAAAAAAAAAmmmmAAAAAAAAmmm',
      'vvAAAAAAAAkAAAmmmmmAAAAAAAmmmmmAAAAAAAAAAAvv',
      'vvAAAAAAAAAAAAAmmmmmmmmmmmmmmmAAAAAAAAAAAAvv',
      'vvAAAAAAAAAAAAAAvvvvvvmmmmvvAAvAAAAAkAAAAAvv',
      'vvAAAAAAAAAAAAAAvvvvvvvvAAvvAAvvvvAAAAAAAAvv',
      'vvvvvvvvvvvvvvAAvvvvvvvvvvvvvvvvvvvvvAvvAAvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvAAAAvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvAAAAAAvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvAAAAAvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    ],
    props: [
      ['fc_topSpire', 21, 0.5],
      ['pillar', 4, 6.6], ['pillar', 39, 6.6], ['pillar', 3, 21.4], ['pillar', 39, 21.4],
      ['brokenPillar', 13, 7.6], ['brokenPillar', 31, 7.6], ['brokenPillar', 12, 22.4], ['brokenPillar', 32, 22.4],
      ['rubble', 8, 12], ['rubble', 34, 12.2], ['rubble', 7, 19], ['rubble', 35, 19.2], ['smallRock', 17, 23], ['smallRock', 27, 9],
      ['crater', 20, 20],
    ],
    enemies: [rival('fc_topBrawler', 10, 14), rival('fc_topBrawler', 34, 17), rival('fc_topGunner', 22, 8)],
    objects: [
      { type: 'flight', x: 36, y: 7, to: 'top_arena_b', tx: 37, ty: 2, label: 'Floating rock' },
      { type: 'flight', x: 35, y: 3, to: 'top_arena_b', tx: 36, ty: 8, label: 'Stage' },
      { type: 'chest', x: 39, y: 3, id: 'fc_cap_topb_1', item: 'pow3' },
      { type: 'flight', x: 8, y: 25, to: 'top_arena_b', tx: 7, ty: 29, label: 'Floating rock' },
      { type: 'flight', x: 9, y: 29, to: 'top_arena_b', tx: 8, ty: 24, label: 'Stage' },
      { type: 'breakable', x: 6, y: 30, size: 2, item: 'end1', id: 'fc_brk_topb_1' },
      { type: 'breakable', x: 28, y: 23, size: 2 },
      { type: 'breakable', x: 15, y: 9, size: 1 },
    ],
    exits: { west: { to: 'top_arena_a' }, east: { to: 'top_arena_c' } },
  },
  {
    id: 'top_arena_c', name: 'Tournament Stage - East Ring', music: 'tournament', hostile: true, ringOut: true,
    region: 'Tournament of Power', backdrop: '#0a0618',
    legend: { 'v': 'void', 'A': 'arena', 'k': 'rock', 'm': 'metal' },
    grid: [
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      'vvAAvvAAvvAAvvAvvvvvvvvvvvvvvvvvvvvvAAvvkvvv',
      'vvAAAAAAAkAAAAAAvvvvvvvvvvvvvvvvAAvvAAvvAvvv',
      'vvAkAAAAAAAAAAAAAAvvvvAAvvvvvvvvAAvvAAAAAvvv',
      'vvAAAAAAAAAAAAAAAAAvAAAAAAvvvAAAAAAAAAAAAvvv',
      'vvAAAAAAAAAAAAAAAAAAAAAAkAvvvAAAAAAAkAAAAvvv',
      'vvAAAAAAAAAAAAAAAAAAAAAAAAvvvAAAAAAAAAAAAvvv',
      'vvAAAAAAAmmmmmmmAAAAAAAmmmmmmmmAAAkAAAAAAvAv',
      'mmmAAAAmmmmAAAmmmmAAAAAmmmmmmmmAAmmmmmAAAvkv',
      'mmmAAAmmAAAAkAAAAmmAAAAAvvvAAAAAmmAAAmmAAAAv',
      'mmmAkmmAAAAAAAAkAAmmAAAAvvvAAAAmAAAAAAAmAAAv',
      'mmmAmmAAAAAAAAAAAAAmmAAAvvvAAAmmAAAAAAAmmAAv',
      'mmmAmmAAAAkAAAAAAAAmmAAAvvvAAAmAAAAAAAAAmkAv',
      'mmmAmmAAAAAAAAAAAAAmmAAkvvvAAAmAAAAAAAAAmAAv',
      'mmmAmmAAAAkAAAAAAAAmmAAAvvvAAAmAAAAAAAAAmAAv',
      'mmmAmmAAAAAAAAAAAAAmmAAAvvvAAAmmAAAAAAAmmAAv',
      'mmmkAmmAAAAAAAAAAAmmAAAAAvvvAAAmAAkAAAAmAAAv',
      'mmmAAAmmAAAAAAAAAmmAAAAAAvvvAAAAmmAAAmmAAAAv',
      'mmmAkAAmmmmAAAmmmmAAAAAmmmmmmmmAAmmmmmAAAAAv',
      'mmmAAAAAAmmmmmmmAAAAAAAmmmmmmmmAAAAAAAAAAAvv',
      'vvAAAAAAAAAAAAAAAAAAAAAAAAvvvAkkAAAAAAAAAvvv',
      'vvAAAAAAkAAAAkAAAAAkAAAAAAvvvAAAkkAAAAAAkvvv',
      'vvkAAAAAAAAAAAAkAAAAAAAAAAvvvAAAAAAAAAAAAvvv',
      'vvAAAAvvAvvvAAAAAAAAAAAAAAvvvAAAAAAAAAAAvvvv',
      'vvvvvvvvvvvvvvAAAAAAAAAAAAvvvAvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvAAAAAAAAAvvvvvvAvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvAAAAAvvvvvvvvvvvvvAAAAvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvAAAkAAAvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvAAAAvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    ],
    props: [
      ['pillar', 4, 5.6], ['pillar', 19, 5.4], ['pillar', 31, 4.6], ['pillar', 39, 5.6], ['pillar', 3, 22], ['pillar', 39, 21.6],
      ['brokenPillar', 21, 12], ['brokenPillar', 30, 13], ['brokenPillar', 10, 22.6], ['brokenPillar', 33, 19],
      ['rubble', 6, 9.2], ['rubble', 17, 18.2], ['rubble', 36, 9.2], ['rubble', 37, 24], ['smallRock', 23, 15], ['smallRock', 29, 18],
      ['crater', 9, 13], ['crater', 33, 14],
    ],
    enemies: [rival('fc_topBrawler', 10, 12), rival('fc_topBrawler', 36, 15), rival('fc_topGunner', 15, 22), rival('fc_topGunner', 34, 8)],
    objects: [
      { type: 'flight', x: 36, y: 24, to: 'top_arena_c', tx: 37, ty: 29, label: 'Floating rock' },
      { type: 'flight', x: 35, y: 29, to: 'top_arena_c', tx: 36, ty: 23, label: 'Stage' },
      { type: 'chest', x: 39, y: 29, id: 'fc_cap_topc_1', item: 'end3' },
      { type: 'breakable', x: 13, y: 8, size: 2 },
      { type: 'breakable', x: 31, y: 22, size: 1 },
      { type: 'breakable', x: 20, y: 24, size: 3 },
    ],
    exits: { west: { to: 'top_arena_b' } },
  },
]);
