/**
 * Hair and headgear masks. Each style has front ('down'), back ('up') and profile ('left') masks.
 * Masks are 16 columns wide; column 0 maps to sprite x=4 and row 0 maps to (headY - 4).
 * The head occupies columns 4..11 (front/back) or 4..10 (profile), rows 4..11.
 * Palette: h = hair, H = hair shade, j = highlight, s = skin, k = accent (band / inner ear / gem).
 */
export interface HairMasks {
  down: string[];
  up: string[];
  left: string[];
  /** Draw behind the body instead of over it (long hair at the back). */
  behind?: { down?: string[]; left?: string[] };
}

export type HairStyle =
  | 'goku' | 'ssj' | 'ssj3' | 'vegeta' | 'gohan' | 'trunks' | 'trunksKid' | 'long' | 'short' | 'spiky'
  | 'bald' | 'turban' | 'catEars' | 'whis' | 'mohawk' | 'bob' | 'bun' | 'ponytail' | 'spikyTail'
  | 'afro' | 'dome' | 'helmet' | 'hat' | 'rabbit' | 'cap' | 'braids' | 'antennae' | 'none';

const GOKU: HairMasks = {
  down: [
    '....h...h..h....',
    '...hh..hh.hh..h.',
    '.h.hhhhhhhhhhhh.',
    '.hhhhhhhhhhhhhhh',
    'hhhhhhhhjhhhhhh.',
    '.hhhhhhjhhhhhhhh',
    'hhhhhhhhhhhhhhhh',
    '..hhhh.hh..hhh..',
    '...hh......hh...',
    '...h........h...',
  ],
  up: [
    '....h...h..h....',
    '...hh..hh.hh..h.',
    '.h.hhhhhhhhhhhh.',
    '.hhhhhhhhhhhhhhh',
    'hhhhhhhhhhhhhhh.',
    '.hhhhhhhhhhhhhhh',
    'hhhhhhhhhhhhhhhh',
    '.hhhhhhhhhhhhhh.',
    '..hhhhhhhhhhhh..',
    '...hhHhhhhHhh...',
    '....h.h..h.h....',
  ],
  left: [
    '.......h..h.....',
    '.....hhh.hh..h..',
    '....hhhhhhhh.hh.',
    '...hhhhhhhhhhhhh',
    '..hhhhhhjhhhhhh.',
    '.hhhhhhhhhhhhhhh',
    'hhh.hhhhhhhhhhh.',
    '....hh.hhhhhhhh.',
    '........hhhhhh..',
    '.........hhhhh..',
    '..........hh.h..',
  ],
};

const SSJ: HairMasks = {
  down: [
    '..h..h..h..h..h.',
    '..hh.hh.hh.hhhh.',
    '.hhhhhhhhhhhhhh.',
    'hhhhhhhjhhhhhhhh',
    '.hhhhhhjhhhhhhh.',
    'hhhhhhhhhhhhhhhh',
    '.hhhhhhhhhhhhhh.',
    '..hhh..hh...hh..',
    '...hh.......hh..',
    '...h.........h..',
  ],
  up: [
    '..h..h..h..h..h.',
    '..hh.hh.hh.hhhh.',
    '.hhhhhhhhhhhhhh.',
    'hhhhhhhhhhhhhhhh',
    '.hhhhhhhhhhhhhh.',
    'hhhhhhhhhhhhhhhh',
    '.hhhhhhhhhhhhhh.',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
    '...hHhhHhhHhh...',
  ],
  left: [
    '.....h..h..h....',
    '....hh.hh.hh..h.',
    '...hhhhhhhhhhhh.',
    '..hhhhhjhhhhhhhh',
    '.hhhhhhhhhhhhhh.',
    'hhhhhhhhhhhhhhhh',
    '...hhhhhhhhhhhh.',
    '....h..hhhhhhh..',
    '........hhhhhh..',
    '.........hhhh...',
  ],
};

const SSJ3: HairMasks = {
  down: [
    '...hhhhhhhhhh...',
    '..hhhhhhjhhhhh..',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '.hhhhhhhhhhhhhh.',
    '.hhhh......hhhh.',
    '.hhh........hhh.',
    '.hhh........hhh.',
    '.hhh........hhh.',
    '.hhh........hhh.',
    '..hh........hh..',
    '..hh........hh..',
    '..h..........h..',
  ],
  up: [
    '...hhhhhhhhhh...',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '.hhhhhhhhhhhhhh.',
    '.hhhhhhhhhhhhhh.',
    '.hhhhhhhhhhhhhh.',
    '.hhhhhhhhhhhhhh.',
    '.hhhhhhhhhhhhhh.',
    '.hhhhHhhhhHhhhh.',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
    '....hhhhhhhh....',
  ],
  left: [
    '....hhhhhhhhh...',
    '...hhhhhjhhhhh..',
    '...hhhhhhhhhhhh.',
    '..hhhhhhhhhhhhh.',
    '.hhhhhhhhhhhhhh.',
    '...hhhhhhhhhhhh.',
    '........hhhhhhh.',
    '........hhhhhhh.',
    '.........hhhhhh.',
    '.........hhhhhh.',
    '.........hhhhhh.',
    '..........hhhhh.',
    '...........hhhh.',
  ],
};

const VEGETA: HairMasks = {
  down: [
    '...h.hh.hh.h....',
    '...hhhhhhhhhh...',
    '..hhhhhhhhhhhh..',
    '..hhhhhhjhhhhh..',
    '...hhhhhhhhhh...',
    '...hhh.hh.hhh...',
    '...hh..hh..hh...',
    '...h........h...',
  ],
  up: [
    '...h.hh.hh.h....',
    '...hhhhhhhhhh...',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhHhhhhHhh...',
    '....hhhhhhhh....',
  ],
  left: [
    '......h.hh.h....',
    '.....hhhhhhhh...',
    '....hhhhhhhhhh..',
    '....hhhhhjhhhh..',
    '.....hhhhhhhhh..',
    '.....hhhhhhhh...',
    '.......hhhhhh...',
    '........hhhhh...',
    '.........hhh....',
  ],
};

const GOHAN: HairMasks = {
  down: [
    '................',
    '................',
    '....h.hh.hh.....',
    '...hhhhhhhhhh...',
    '..hhhhhhjhhhhh..',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
    '...hh..hh..hh...',
    '...h........h...',
  ],
  up: [
    '................',
    '................',
    '....h.hh.hh.....',
    '...hhhhhhhhhh...',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '....hhHhhHhh....',
  ],
  left: [
    '................',
    '................',
    '.....h.hh.h.....',
    '....hhhhhhhhh...',
    '...hhhhhjhhhhh..',
    '..hhhhhhhhhhhh..',
    '...h.hhhhhhhhh..',
    '.......hhhhhh...',
    '........hhhhh...',
    '.........hhh....',
  ],
};

const TRUNKS: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhjhhhh...',
    '...hhhhhhhhhhh..',
    '...hhhh..hhhhh..',
    '...hhh....hhh...',
    '...hh......hh...',
    '...hh......hh...',
    '...h........h...',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '....hHhhhhHhh...',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhhjhhhhh..',
    '...hhhhhhhhhhh..',
    '...hh.hhhhhhhh..',
    '...h...hhhhhhh..',
    '.......hhhhhhh..',
    '........hhhhhh..',
    '.........hhhh...',
  ],
};

const TRUNKS_KID: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhjhhhh...',
    '...hhhhhhhhhhh..',
    '...hhhh..hhhhh..',
    '...hh......hh...',
    '...h........h...',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '....hHhhhhHhh...',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhhjhhhhh..',
    '...hhhhhhhhhhh..',
    '...hh.hhhhhhhh..',
    '.......hhhhhh...',
    '........hhhh....',
  ],
};

const LONG: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhjhhhh...',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhh....hhhh..',
    '...hh......hh...',
    '...hh......hh...',
    '...hh......hh...',
    '...hh......hh...',
    '...hh......hh...',
    '...h........h...',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '....hHhHhhHhh...',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhhjhhhhh..',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhh..',
    '...h...hhhhhhh..',
    '.......hhhhhhh..',
    '.......hhhhhhh..',
    '........hhhhhh..',
    '........hhhhhh..',
    '........hhhhh...',
    '.........hhhh...',
  ],
};

const SHORT: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhjhhhh...',
    '...hhhhhhhhhh...',
    '...hh......hh...',
    '...h........h...',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '....hHhhhHhh....',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhhjhhhh...',
    '...hhhhhhhhhh...',
    '...h...hhhhhh...',
    '.......hhhhhh...',
    '........hhhh....',
  ],
};

const SPIKY: HairMasks = {
  down: [
    '................',
    '.....h..h..h....',
    '....hh.hh.hh....',
    '...hhhhhhhhhh...',
    '..hhhhhjhhhhhh..',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
    '...hh.h..h.hh...',
    '...h........h...',
  ],
  up: [
    '................',
    '.....h..h..h....',
    '....hh.hh.hh....',
    '...hhhhhhhhhh...',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '....hHhhHhhh....',
  ],
  left: [
    '................',
    '......h..h......',
    '.....hh.hh.h....',
    '....hhhhhhhhh...',
    '...hhhhjhhhhhh..',
    '..hhhhhhhhhhhh..',
    '...h.hhhhhhhhh..',
    '.......hhhhhh...',
    '........hhhhh...',
  ],
};

const BALD: HairMasks = { down: [], up: [], left: [] };

const TURBAN: HairMasks = {
  down: [
    '................',
    '................',
    '.....hhhhhh.....',
    '....hhhhjhhh....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....kkkkkkkk....',
  ],
  up: [
    '................',
    '................',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....kkkkkkkk....',
    '....hhhhhhhh....',
  ],
  left: [
    '................',
    '................',
    '.....hhhhhh.....',
    '....hhhjhhhh....',
    '....hhhhhhhhh...',
    '....hhhhhhhhh...',
    '....kkkkkkkkk...',
    '........hhhh....',
  ],
};

const CAT_EARS: HairMasks = {
  down: [
    '..hh........hh..',
    '..hkh......hkh..',
    '..hkkh....hkkh..',
    '...hkhh..hhkh...',
    '....hh....hh....',
  ],
  up: [
    '..hh........hh..',
    '..hhh......hhh..',
    '..hhhh....hhhh..',
    '...hhhh..hhhh...',
    '....hh....hh....',
  ],
  left: [
    '.......hh.......',
    '.......hkh......',
    '.......hkkh.....',
    '........hkhh....',
    '.........hh.....',
  ],
};

const WHIS: HairMasks = {
  down: [
    '.....hhhhhh.....',
    '.....hhhjhh.....',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....h......h....',
  ],
  up: [
    '.....hhhhhh.....',
    '.....hhhhhh.....',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....hHhhhhHh....',
  ],
  left: [
    '.....hhhhhh.....',
    '.....hhhjhh.....',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '....hhhhhhhhh...',
    '.......hhhhhh...',
  ],
};

const MOHAWK: HairMasks = {
  down: [
    '................',
    '.......hh.......',
    '......hhhh......',
    '......hhjh......',
    '......hhhh......',
    '.......hh.......',
  ],
  up: [
    '................',
    '.......hh.......',
    '......hhhh......',
    '......hhhh......',
    '......hhhh......',
    '.......hh.......',
  ],
  left: [
    '................',
    '.......hhh......',
    '......hhhhhh....',
    '......hhjhhhh...',
    '.......hhhhh....',
    '........hhh.....',
  ],
};

const BOB: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhjhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hh......hh...',
    '...hh......hh...',
    '...hh......hh...',
    '...hhh....hhh...',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhHhhhhHhh...',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhhjhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...h...hhhhhh...',
    '.......hhhhhh...',
    '.......hhhhhh...',
    '.......hhhhhh...',
  ],
};

const BUN: HairMasks = {
  down: [
    '......hhhh......',
    '.....hhjhhh.....',
    '......hhhh......',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hh.hhhh.hh...',
    '...h........h...',
  ],
  up: [
    '......hhhh......',
    '.....hhhhhh.....',
    '......hHhh......',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '....hhhhhhhh....',
  ],
  left: [
    '..........hhh...',
    '.........hhjhh..',
    '.........hhhh...',
    '.....hhhhhhh....',
    '....hhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hh..hhhhhh...',
    '.......hhhhh....',
  ],
};

const PONYTAIL: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhjhhhh...',
    '...hhhhhhhhhh...',
    '...hh.hhhh.hh...',
    '...h........h...',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhkkhhhh...',
    '....hhhhhhhh....',
    '......hhhh......',
    '......hhhh......',
    '.......hh.......',
    '.......hh.......',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhhjhhhh...',
    '...hhhhhhhhhhk..',
    '...hh..hhhhhhkh.',
    '.......hhhhh..hh',
    '..............hh',
    '..............h.',
  ],
};

const SPIKY_TAIL: HairMasks = {
  down: [
    '..h...h..h...h..',
    '..hh.hhhhhh.hh..',
    '..hhhhhhhhhhhh..',
    '..hhhhhhjhhhhh..',
    '...hhhhhhhhhh...',
    '...hh.hhhh.hh...',
    '...h........h...',
  ],
  up: [
    '..h...h..h...h..',
    '..hh.hhhhhh.hh..',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '....hhhkkhhh....',
    '.....hhhhhh.....',
    '......hhhh......',
    '.......hh.......',
  ],
  left: [
    '....h..h..h.....',
    '....hhhhhhhhh...',
    '...hhhhhjhhhhh..',
    '...hhhhhhhhhhhh.',
    '....hhhhhhhhhk..',
    '...h..hhhhhhhkh.',
    '.......hhhhh.hhh',
    '.............hh.',
  ],
};

const AFRO: HairMasks = {
  down: [
    '................',
    '....hhhhhhhh....',
    '...hhhhhhjhhh...',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '..hhh......hhh..',
    '..hh........hh..',
  ],
  up: [
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '..hhhhhhhhhhhh..',
    '...hhhhhhhhhh...',
  ],
  left: [
    '................',
    '....hhhhhhhh....',
    '...hhhhhhjhhh...',
    '...hhhhhhhhhhh..',
    '...hhhhhhhhhhhh.',
    '...hhhhhhhhhhhh.',
    '....h...hhhhhhh.',
    '........hhhhhh..',
  ],
};

const DOME: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '.....hhhhhh.....',
    '....hhhjhhhh....',
    '....hhhhhhhh....',
    '....kkkkkkkk....',
  ],
  up: [
    '................',
    '................',
    '................',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '....kkkkkkkk....',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhh.....',
    '....hhjhhhhh....',
    '....hhhhhhhhh...',
    '....kkhhhhhhh...',
    '........hhhh....',
  ],
};

const HELMET: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhjhhhhh...',
    '...hhhhhhhhhh...',
    '...hkkkkkkkkh...',
    '...hh......hh...',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhjhhhhh...',
    '...hhhhhhhhhh...',
    '...kkkkhhhhhh...',
    '.......hhhhhh...',
  ],
};

const HAT: HairMasks = {
  down: [
    '................',
    '.....hhhhhh.....',
    '....hhhhjhhh....',
    '....hhhhhhhh....',
    '..kkkkkkkkkkkk..',
    '..hhhhhhhhhhhh..',
  ],
  up: [
    '................',
    '.....hhhhhh.....',
    '....hhhhhhhh....',
    '....hhhhhhhh....',
    '..kkkkkkkkkkkk..',
    '..hhhhhhhhhhhh..',
  ],
  left: [
    '................',
    '.....hhhhhh.....',
    '....hhhjhhhh....',
    '....hhhhhhhh....',
    '.kkkkkkkkkkkkk..',
    '.hhhhhhhhhhhhh..',
  ],
};

const RABBIT: HairMasks = {
  down: [
    '...hh......hh...',
    '...hkh....hkh...',
    '...hkh....hkh...',
    '...hkh....hkh...',
    '....hh....hh....',
  ],
  up: [
    '...hh......hh...',
    '...hhh....hhh...',
    '...hhh....hhh...',
    '...hhh....hhh...',
    '....hh....hh....',
  ],
  left: [
    '........hh......',
    '........hkh.....',
    '........hkh.....',
    '........hkh.....',
    '.........hh.....',
  ],
};

const CAP: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhjhhhhh...',
    '...hhhhhhhhhh...',
    '...kkkkkkkkkk...',
    '...hh......hh...',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhjhhhhh...',
    '...hhhhhhhhhh...',
    'kkkkkkkhhhhhh...',
    '.......hhhhhh...',
  ],
};

const BRAIDS: HairMasks = {
  down: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhjhhhh...',
    '...hhhhhhhhhh...',
    '...hh.hhhh.hh...',
    '..hh........hh..',
    '..hh........hh..',
    '..kk........kk..',
    '..hh........hh..',
    '..h..........h..',
  ],
  up: [
    '................',
    '................',
    '................',
    '....hhhhhhhh....',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '...hhhhhhhhhh...',
    '..hhhhhhhhhhhh..',
    '..hh........hh..',
    '..kk........kk..',
    '..hh........hh..',
    '..h..........h..',
  ],
  left: [
    '................',
    '................',
    '................',
    '.....hhhhhhh....',
    '....hhhhjhhhh...',
    '...hhhhhhhhhh...',
    '...hh..hhhhhh...',
    '.........hhhh...',
    '.........hh.....',
    '.........kk.....',
    '.........hh.....',
    '.........h......',
  ],
};

const ANTENNAE: HairMasks = {
  down: [
    '...h........h...',
    '....h......h....',
    '....h......h....',
    '.....h....h.....',
    '.....h....h.....',
  ],
  up: [
    '...h........h...',
    '....h......h....',
    '....h......h....',
    '.....h....h.....',
    '.....h....h.....',
  ],
  left: [
    '..h.............',
    '...h............',
    '....h...........',
    '.....h..........',
    '......h.........',
  ],
};

/** All hair masks by style. */
export const HAIR: Record<HairStyle, HairMasks> = {
  goku: GOKU, ssj: SSJ, ssj3: SSJ3, vegeta: VEGETA, gohan: GOHAN, trunks: TRUNKS, trunksKid: TRUNKS_KID,
  long: LONG, short: SHORT, spiky: SPIKY, bald: BALD, turban: TURBAN, catEars: CAT_EARS, whis: WHIS,
  mohawk: MOHAWK, bob: BOB, bun: BUN, ponytail: PONYTAIL, spikyTail: SPIKY_TAIL, afro: AFRO, dome: DOME,
  helmet: HELMET, hat: HAT, rabbit: RABBIT, cap: CAP, braids: BRAIDS, antennae: ANTENNAE, none: BALD,
};
