import { registerMaps } from '../../registry';

/**
 * Act 3 chapter maps.
 *  - c06_void: what is left of Earth after Frieza's last attack (Whis's barrier bubble in open space).
 *  - c07_nameless_grounds: the crater floor of the Nameless Planet inside Vados's dome (team camps, exam hall,
 *    concessions, stadium entrance). c07_nameless_arena: the ring over the void (`ringOut`) with both benches and
 *    spectator stands. c07_nameless_rim: hostile debris field on the crater rim.
 *  - c08_potaufeu_landing / _mushrooms / _vault: Potaufeu (landing site, giant-mushroom forest, Commeson vault).
 *
 * Key coordinates used by the scripts are exported in `SPOTS` (see c07.ts / c08.ts).
 */

/** Both teams on the Nameless Planet from the arrival (Whis's cube) until the exam; before that they are on Earth. */
const U7_TEAM = 'chapter==7&c07_departed&!c07_examDone';
const ARENA = 'chapter==7&c07_examDone&!c07_done';

/**
 * The three "Superhuman Water" jars in the mushroom forest (silver quest c08_water). Water broken out of a jar but
 * never picked up waits where it fell (the engine keeps id'd breakable drops until they are collected).
 */
export const C08_JARS = [
  { id: 'c08_jar1', x: 6, y: 8 },
  { id: 'c08_jar2', x: 38, y: 4 },
  { id: 'c08_jar3', x: 34, y: 24 },
] as const;

registerMaps([
  // ------------------------------------------------------------------ Chapter 6: the destroyed Earth
  {
    id: 'c06_void', name: 'Where Earth Was', music: 'sad', region: 'Rocky Wasteland', backdrop: '#07040f',
    legend: { v: 'void', c: 'cloud' },
    grid: [
      'vvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvccccccvvvvvvvv',
      'vvvvvvvccccccccvvvvvvv',
      'vvvvvvccccccccccvvvvvv',
      'vvvvvvccccccccccvvvvvv',
      'vvvvvvvccccccccvvvvvvv',
      'vvvvvvvvccccccvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvv',
    ],
    props: [
      ['c06_barrier', 5.5, 4], ['c06_earthChunk', 1, 2], ['c06_earthChunk', 17, 11], ['c06_earthChunk', 18, 5.5],
      ['floatingRock', 15.5, 1.5], ['floatingRock', 2, 11], ['floatingRock', 7, 12.5], ['c06_earthChunk', 3.5, 6.5],
    ],
  },

  // ------------------------------------------------------------------ Chapter 7: the Nameless Planet
  {
    id: 'c07_nameless_grounds', name: 'Nameless Planet', music: 'tournament', region: 'Nameless Planet',
    legend: { '#': 'cliff', '.': 'rock', ',': 'wasteland', d: 'dirt', '=': 'path', m: 'marble', W: 'wall', R: 'roof', t: 'tile' },
    grid: [
      '###########RRRRRRRmmmmRRRRRRR###########',
      '#####..###.RRRRRRRmmmmRRRRRRR..##..#####',
      '###,.....,.WWWWWWWmmmmWWWWWWW,.,.....###',
      '##.,.....,,WWWWWWWmmmmWWWWWWW.,...,.,.##',
      '#..........WWWWWWWmmmmWWWWWWW..........#',
      '#...........mmmmmmmmmmmmmmmm.........,.#',
      '#,.,........mmmmmmmmmmmmmmmm..,.,......#',
      '#.ddddddddd.mmmmmmmmmmmmmmmm.ddddddddd.#',
      '#.ddddddddd.mmmmmmmmmmmmmmmm.ddddddddd.#',
      '#.ddddddddd.mmmmmmmmmmmmmmmm,ddddddddd.#',
      '#.ddddddddd.mmmmmmmmmmmmmmmm.ddddddddd.#',
      '#.ddddddddd.mmmmmmmmmmmmmmmmdddddddddd,#',
      '#.ddddddddd.d.mmmm====mmmm.ddddddddddd.#',
      '#...================================...#',
      '#..,================================...#',
      '#..dddddddddd,..,,====dddd==.dddddddd..#',
      '#..dddddddd.d.d.,.====.ddd==.dddddddd..#',
      '#..dddddddddddddd.====..dd==.dddddddd..#',
      '#..dddddddd.d..ddd====.,..==.dddddddd,.#',
      '#..,......,..WWWWWttttWWW.==..,.,......#',
      '#............WttttttttttW,==..,........#',
      '#.,tttttttt..WttttttttttW.==........,...',
      '#..tttttttt,.WttttttttttW.==============',
      '#..tttttttt..tttttttttttt,==============',
      '#,.tttttttt..tttttttttttt.........,.....',
      '#..tttttttt.,.........,.,...,.###......#',
      '##...,..,......,..............###..,..##',
      '###.,..,...................,.......,.###',
      '#####............,......,..........#####',
      '########################################',
    ],
    props: [
      // Stadium frontage.
      ['c07_banner', 11, 4.6], ['c07_banner', 28, 4.6], ['statue', 13, 6.4], ['statue', 25.6, 6.4],
      ['lamp', 12.4, 9], ['lamp', 27, 9], ['lamp', 14.6, 11], ['lamp', 24.8, 11], ['c07_scoreboard', 13.6, 8.6],
      ['flowers', 16, 6], ['flowers', 22.5, 6.2], ['flowers', 16.4, 10.2], ['flowers', 22, 10],
      // Universe 7 camp.
      ['c07_cubeU7', 2, 7], ['campfire', 6, 10.4], ['tent', 3.5, 15.4], ['crate', 10.2, 15.6], ['barrel', 11.4, 15.8],
      // Universe 6 camp.
      ['c07_cubeU6', 34, 7], ['campfire', 31, 10.4], ['tent', 31.5, 15.4], ['crate', 28.6, 15.6], ['jar', 30, 17.6],
      // Exam hall desks.
      ['table', 14.5, 21], ['table', 21, 21], ['table', 14.5, 23.2], ['table', 21, 23.2], ['plant', 23.2, 20],
      // Concessions and the restrooms.
      ['counter', 3.5, 21], ['barrel', 9.6, 21], ['crate', 3.2, 24.5], ['jar', 4.6, 24.6], ['hut', 6.5, 24],
      // Barren crater floor.
      ['boulder', 32.6, 2.2], ['rock', 4, 3.2], ['brokenPillar', 2.6, 4.4], ['rock', 35, 19.6], ['rock', 2, 18.8],
      ['smallRock', 30, 23], ['crater', 9, 26.6], ['crater', 22.5, 26.4], ['rubble', 35.6, 25.4], ['smallRock', 14, 27],
      ['deadTree', 37, 3.4], ['grassTuft', 26, 25], ['grassTuft', 6, 19.5],
      // Super Shenron rises over the stadium during the finale (shown only while the flag is set).
      { kind: 'c07_superShenron', x: 11, y: 2, id: 'c07_shenronProp', flag: 'c07_shenronUp', hideFlag: 'c07_shenronGone' },
    ],
    npcs: [
      // Team Universe 7 before the exam (the active character is never doubled as an NPC).
      { id: 'c07_g_beerus', sprite: 'beerus', x: 4, y: 11, dir: 'right', talk: 'c07_beerus_talk', name: 'Beerus', showIf: U7_TEAM },
      { id: 'c07_g_monaka', sprite: 'monaka', x: 2, y: 12, dir: 'right', talk: 'c07_monaka_talk', name: 'Monaka', showIf: U7_TEAM },
      { id: 'c07_g_buu', sprite: 'majinBuu', x: 7, y: 12, talk: 'c07_buu_talk', name: 'Buu', showIf: U7_TEAM, wander: 1 },
      { id: 'c07_g_goku', sprite: 'goku', x: 10, y: 11, dir: 'left', talk: 'c07_teammate_talk', name: 'Goku', showIf: `${U7_TEAM}&!char:goku` },
      { id: 'c07_g_vegeta', sprite: 'vegeta', x: 9, y: 12, dir: 'up', talk: 'c07_teammate_talk', name: 'Vegeta', showIf: `${U7_TEAM}&!char:vegeta` },
      { id: 'c07_g_piccolo', sprite: 'piccolo', x: 3, y: 13, dir: 'right', talk: 'c07_teammate_talk', name: 'Piccolo', showIf: `${U7_TEAM}&!char:piccolo` },
      // Whis studies the crater rim until the orange stones are in; then he joins Lord Beerus in the gods' box.
      { id: 'c07_g_whis', sprite: 'whis', x: 9, y: 9, dir: 'down', talk: 'c07_whis_grounds', name: 'Whis', showIf: 'chapter==7&c07_departed&world:space', hideIf: 'c07_examDone&done:c07_shards' },
      // Whis comes back for the orange stones if that quest is still open after the tournament (on Earth he is at
      // Capsule Corp, the ride back out here; in Universe 10 with Lord Beerus while that case is open).
      { id: 'c07_g_whis2', sprite: 'whis', x: 9, y: 9, dir: 'down', talk: 'c07_whis_grounds', name: 'Whis', showIf: 'chapter>=8&quest:c07_shards&world:space', hideIf: 'quest:c10_q_u10' },
      // Team Universe 6.
      { id: 'c07_g_champa', sprite: 'champa', x: 33, y: 11, dir: 'left', talk: 'c07_champa_talk', name: 'Champa', showIf: U7_TEAM },
      { id: 'c07_g_cabba', sprite: 'cabba', x: 30, y: 12, dir: 'left', talk: 'c07_cabba_talk', name: 'Cabba', showIf: U7_TEAM },
      { id: 'c07_g_frost', sprite: 'frost', x: 36, y: 12, dir: 'left', talk: 'c07_frost_talk', name: 'Frost', showIf: U7_TEAM },
      { id: 'c07_g_hit', sprite: 'hit', x: 37, y: 16, dir: 'left', talk: 'c07_hit_talk', name: 'Hit', showIf: U7_TEAM },
      { id: 'c07_g_botamo', sprite: 'botamo', x: 30, y: 17, dir: 'left', talk: 'c07_botamo_talk', name: 'Botamo', showIf: U7_TEAM },
      { id: 'c07_g_magetta', sprite: 'c07_magetta', x: 34, y: 18, dir: 'left', talk: 'c07_magetta_talk', name: 'Magetta', showIf: U7_TEAM },
      // The exam proctor.
      { id: 'c07_g_vados', sprite: 'vados', x: 19, y: 21, dir: 'down', talk: 'c07_vados_exam', name: 'Vados', showIf: U7_TEAM },
      // Staff of the neutral zone (stay after the tournament).
      { id: 'c07_g_vendor', sprite: 'c07_vendor', x: 8, y: 22, dir: 'down', talk: 'c07_vendor_talk', name: 'Snack Vendor', showIf: 'chapter>=7' },
      { id: 'c07_g_attendant', sprite: 'c07_attendant', x: 22, y: 5, dir: 'down', talk: 'c07_attendant_talk', name: 'Arena Attendant', showIf: 'chapter>=7' },
    ],
    warps: [
      { x: 18, y: 0, w: 4, h: 1, to: 'c07_nameless_arena', tx: 17.5, ty: 27, dir: 'up', showIf: 'c07_examDone', lockedScript: 'c07_arena_locked' },
    ],
    exits: { east: { to: 'c07_nameless_rim' } },
    objects: [
      { type: 'save', x: 8, y: 7 },
      { type: 'worldSign', x: 6, y: 7 },
      { type: 'sign', x: 17, y: 18, text: 'WRITTEN EXAM HALL. Pencils provided. Telepathy, time-skips and copying from gods are prohibited.' },
      { type: 'sign', x: 9, y: 25, text: 'RESTROOMS. Universe 6 on the left, Universe 7 on the right. Gods of Destruction: please use your own planet.' },
      { type: 'sign', x: 37, y: 20, text: 'CRATER RIM. Debris field ahead. Vados\'s barrier keeps the air in, but not the wildlife out.' },
    ],
  },
  {
    id: 'c07_nameless_arena', name: 'Tournament Ring', music: 'tournament', region: 'Nameless Planet', backdrop: '#140c28',
    ringOut: true,
    legend: { W: 'wall', o: 'wood', m: 'marble', v: 'void', a: 'arena' },
    grid: [
      'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WoooooooooooooooommooooooooooooooooW',
      'WoooooooooooooooommooooooooooooooooW',
      'WoooooooooooooooommooooooooooooooooW',
      'WmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmW',
      'WmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmW',
      'WoooooomvvvvvvvvvvvvvvvvvvvvmooooooW',
      'WoooooomvvvvvvvvvvvvvvvvvvvvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvaaaaaaaaaaaaaaaavvmooooooW',
      'WoooooomvvvvvvvvvvvvvvvvvvvvmooooooW',
      'WoooooomvvvvvvvvvvvvvvvvvvvvmooooooW',
      'WmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmW',
      'WoooooooooooooooommooooooooooooooooW',
      'WoooooooooooooooommooooooooooooooooW',
      'WoooooooooooooooommooooooooooooooooW',
      'WoooooooooooooooommooooooooooooooooW',
      'WoooooooooooooooommooooooooooooooooW',
      'WmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmW',
      'WWWWWWWWWWWWWWWWmmmmWWWWWWWWWWWWWWWW',
    ],
    props: [
      ['throne', 8, 1], ['throne', 25, 1], ['c07_scoreboard', 15.5, 0.2],
      ['c07_portraitBeerus', 8, 11], ['c07_portraitChampa', 26, 11],
      ['lamp', 7, 4.2], ['lamp', 28, 4.2], ['lamp', 7, 20.6], ['lamp', 28, 20.6],
      ['c07_banner', 1.2, 4.6], ['c07_banner', 33.8, 4.6],
      ['c07_bench', 1.5, 8.6], ['c07_bench', 1.5, 18.6], ['c07_bench', 31.5, 8.6], ['c07_bench', 31.5, 18.6],
      ['c07_bench', 2, 26.4], ['c07_bench', 8, 26.4], ['c07_bench', 22, 26.4], ['c07_bench', 28, 26.4],
      ['plant', 14.6, 1.2], ['plant', 19.6, 1.2], ['jar', 33, 1.4], ['barrel', 1.4, 1.2],
    ],
    npcs: [
      // Ring official.
      { id: 'c07_a_announcer', sprite: 'c07_announcer', x: 7, y: 13, dir: 'left', talk: 'c07_announcer_talk', name: 'Announcer', showIf: ARENA },
      // Universe 7 bench (the active fighter is the player).
      { id: 'c07_a_goku', sprite: 'goku', x: 2, y: 11, dir: 'right', talk: 'c07_teammate_talk', name: 'Goku', showIf: `${ARENA}&!char:goku` },
      { id: 'c07_a_vegeta', sprite: 'vegeta', x: 4, y: 12, dir: 'right', talk: 'c07_teammate_talk', name: 'Vegeta', showIf: `${ARENA}&!char:vegeta` },
      { id: 'c07_a_piccolo', sprite: 'piccolo', x: 2, y: 15, dir: 'right', talk: 'c07_teammate_talk', name: 'Piccolo', showIf: `${ARENA}&!char:piccolo` },
      { id: 'c07_a_monaka', sprite: 'monaka', x: 4, y: 16, dir: 'right', talk: 'c07_monaka_talk', name: 'Monaka', showIf: ARENA },
      // Universe 6 bench.
      { id: 'c07_a_botamo', sprite: 'botamo', x: 30, y: 8, dir: 'left', talk: 'c07_botamo_talk', name: 'Botamo', showIf: ARENA, hideIf: 'c07_m1' },
      { id: 'c07_a_frost', sprite: 'frost', x: 33, y: 10, dir: 'left', talk: 'c07_frost_talk', name: 'Frost', showIf: ARENA, hideIf: 'c07_m4' },
      { id: 'c07_a_magetta', sprite: 'c07_magetta', x: 30, y: 12, dir: 'left', talk: 'c07_magetta_talk', name: 'Magetta', showIf: ARENA, hideIf: 'c07_m5' },
      { id: 'c07_a_cabba', sprite: 'cabba', x: 33, y: 14, dir: 'left', talk: 'c07_cabba_talk', name: 'Cabba', showIf: ARENA },
      { id: 'c07_a_hit', sprite: 'hit', x: 30, y: 17, dir: 'left', talk: 'c07_hit_talk', name: 'Hit', showIf: ARENA },
      // Gods' box (north stands).
      { id: 'c07_a_beerus', sprite: 'beerus', x: 9, y: 3, dir: 'down', talk: 'c07_beerus_talk', name: 'Beerus', showIf: ARENA },
      // In space only: a player who flies home between matches finds him at Capsule Corp, the ride back out here.
      { id: 'c07_a_whis', sprite: 'whis', x: 11, y: 3, dir: 'down', talk: 'c07_whis_arena', name: 'Whis', showIf: `${ARENA}&done:c07_shards&world:space` },
      { id: 'c07_a_champa', sprite: 'champa', x: 26, y: 3, dir: 'down', talk: 'c07_champa_talk', name: 'Champa', showIf: ARENA },
      { id: 'c07_a_vados', sprite: 'vados', x: 24, y: 3, dir: 'down', talk: 'c07_vados_arena', name: 'Vados', showIf: ARENA },
      { id: 'c07_a_kai', sprite: 'supremeKai', x: 5, y: 2, dir: 'down', talk: 'c07_kai_talk', name: 'Supreme Kai', showIf: ARENA },
      { id: 'c07_a_oldkai', sprite: 'oldKai', x: 3, y: 2, dir: 'down', talk: 'c07_oldkai_talk', name: 'Old Kai', showIf: ARENA },
      // Spectators (south stands).
      { id: 'c07_a_bulma', sprite: 'bulma', x: 10, y: 24, dir: 'up', talk: 'c07_bulma_arena', name: 'Bulma', showIf: ARENA },
      { id: 'c07_a_krillin', sprite: 'krillin', x: 12, y: 24, dir: 'up', talk: 'c07_krillin_arena', name: 'Krillin', showIf: ARENA },
      { id: 'c07_a_18', sprite: 'android18', x: 13, y: 25, dir: 'up', talk: 'c07_18_arena', name: 'Android 18', showIf: ARENA },
      { id: 'c07_a_roshi', sprite: 'roshi', x: 6, y: 24, dir: 'up', talk: 'c07_roshi_arena', name: 'Master Roshi', showIf: ARENA },
      { id: 'c07_a_yamcha', sprite: 'yamcha', x: 4, y: 25, dir: 'up', talk: 'c07_yamcha_arena', name: 'Yamcha', showIf: ARENA },
      { id: 'c07_a_jaco', sprite: 'jaco', x: 20, y: 24, dir: 'up', talk: 'c07_jaco_arena', name: 'Jaco', showIf: ARENA },
      { id: 'c07_a_galking', sprite: 'c07_galacticKing', x: 22, y: 24, dir: 'up', talk: 'c07_galking_talk', name: 'Galactic King', showIf: ARENA },
      { id: 'c07_a_chichi', sprite: 'chichi', x: 25, y: 24, dir: 'up', talk: 'c07_chichi_arena', name: 'Chi-Chi', showIf: ARENA },
      { id: 'c07_a_goten', sprite: 'goten', x: 27, y: 25, dir: 'up', talk: 'c07_kids_arena', name: 'Goten', showIf: ARENA, wander: 1 },
      { id: 'c07_a_trunks', sprite: 'trunksKid', x: 29, y: 25, dir: 'up', talk: 'c07_kids_arena', name: 'Trunks', showIf: ARENA, wander: 1 },
      { id: 'c07_a_buu', sprite: 'majinBuu', x: 32, y: 26, dir: 'down', talk: 'c07_buu_talk', name: 'Buu', showIf: ARENA },
    ],
    warps: [{ x: 16, y: 29, w: 4, h: 1, to: 'c07_nameless_grounds', tx: 19.5, ty: 2, dir: 'down' }],
    onEnter: 'c07_arena_enter',
    objects: [
      { type: 'save', x: 4, y: 7 },
      { type: 'sign', x: 31, y: 21, text: 'TOURNAMENT RULES: Knock-out, ring-out or surrender. No killing. No weapons. Gods of Destruction must remain seated.' },
    ],
  },
  {
    id: 'c07_nameless_rim', name: 'Crater Rim', music: 'alien', hostile: true, region: 'Nameless Planet',
    legend: { '#': 'cliff', '.': 'rock', ',': 'wasteland', s: 'sand', d: 'dirt' },
    grid: [
      '####################################',
      '####################################',
      '####################################',
      '#######...,,............,........###',
      '####dd.,,..........,###,,....,...###',
      '####dd......,,......###.ssss...,.###',
      '#######.#########,..###.ssss.,.s.###',
      '######..#########s..###.,...,.sss###',
      '######.,###...,ss.s.###..,..,.,s,###',
      '####.,..###,....s...###...######.###',
      '####....###.s..s,,.,###...######.###',
      '####....###..s###s..###,..###.,,..,#',
      '####..,.###..s###ss.###.,.###.,....#',
      '#....,..###..s###,.......,###......#',
      '#####,.,###..s###........,###,######',
      '#####,.,......###.,.....,.###.######',
      '#####.......,.###......,..###.######',
      '#####.........########,...###.######',
      '#####...,.....########....###..ddd##',
      '#####.....,........,..ss.......ddd##',
      '#,.,.,,.....,.,.......s.s......ddd##',
      '..,..,...............,.s####..######',
      '..,..,.....,...,....,...####..sss..#',
      '..,.,.......,..,........####sss..s.#',
      '.,........,.,...........####s.ss.ss#',
      '####################################',
      '####################################',
      '####################################',
    ],
    props: [
      ['rubble', 9, 23.6], ['rubble', 13, 3.4], ['rubble', 26.5, 16], ['crater', 18.5, 21.4], ['crater', 9.5, 19.4],
      ['floatingRock', 20.5, 6], ['floatingRock', 5, 9.6], ['pod', 12, 13.6], ['brokenPillar', 25, 13.4],
      ['spaceship', 23.2, 20], ['brokenPillar', 31.4, 12.2], ['smallRock', 17, 15], ['smallRock', 33, 4], ['rock', 29.4, 3.4],
      ['deadTree', 6.4, 15.4], ['deadTree', 18.4, 3.2], ['crater', 26.4, 5.4],
    ],
    enemies: [
      { type: 'c07_debrisCrawler', x: 10, y: 4 }, { type: 'c07_debrisCrawler', x: 24, y: 16 }, { type: 'c07_debrisCrawler', x: 12, y: 21 },
      { type: 'c07_rockWisp', x: 17, y: 9 }, { type: 'c07_rockWisp', x: 28, y: 6 }, { type: 'c07_rockWisp', x: 31, y: 23 },
      { type: 'c07_debrisGolem', x: 22, y: 14 }, { type: 'c07_debrisGolem', x: 6, y: 13 },
      { type: 'c07_debrisCrawler', x: 19, y: 20 }, { type: 'c07_debrisGolem', x: 30, y: 8 },
    ],
    pickups: [
      { id: 'c07_shard1', item: 'c07_starShard', x: 25, y: 5 },
      { id: 'c07_shard2', item: 'c07_starShard', x: 30, y: 24, hidden: true },
      { id: 'c07_crate', item: 'c07_snackCrate', x: 21, y: 23, showIf: 'quest:c07_snacks' },
    ],
    barriers: [
      { id: 'c07_v27', x: 6, y: 4, w: 1, h: 2, level: 27, character: 'vegeta' },
      { id: 'c07_g28', x: 30, y: 18, w: 1, h: 3, level: 28, character: 'goku' },
    ],
    objects: [
      { type: 'chest', x: 4, y: 4, id: 'c07_rimChestV', item: 'pow3' },
      { type: 'chest', x: 32, y: 19, id: 'c07_rimChestG', item: 'c07_starShard' },
      { type: 'breakable', x: 3, y: 23, size: 2 }, { type: 'breakable', x: 16, y: 5, size: 1 },
      { type: 'breakable', x: 31, y: 11, size: 3, item: 'end1', id: 'c07_rimRock' }, { type: 'breakable', x: 11, y: 16, size: 2 },
    ],
    exits: { west: { to: 'c07_nameless_grounds' } },
  },

  // ------------------------------------------------------------------ Chapter 8: Potaufeu
  {
    id: 'c08_potaufeu_landing', name: 'Potaufeu', music: 'alien', region: 'Potaufeu',
    legend: { '#': 'cliff', s: 'sand', d: 'dirt', g: 'alienGrass', M: 'metal', '=': 'path', r: 'rock', '~': 'water' },
    grid: [
      '##################ddddd#################',
      '##################ddddd#################',
      '####sssssdds######ddddd#####sssdsss#####',
      '####ddsssdss######ddddd#####sssssss#####',
      '####ssssddssssgsdsd===sssssssssdsss#####',
      '####sdsssssgggsssss===ssssssssssdss#####',
      '####ssssgsggggsssss===ssdssssssssss#####',
      '####sssggggggggdsss===ssssdssssdsdsssss#',
      '#dssssssgssggsgssss===sssssssssssssssds#',
      '#sssssssssssgggggsg===ssssssssdrrrssssd#',
      '#ssssMMMMMMMMMMMsgg===ssdssssssrrrsssds#',
      '#ssssMMMMMMMMMMMssg===sssssdsssssssssss#',
      '#ssssMMMMMMMMMMMsss===sssssssssddssssss#',
      '#sdssMMMMMMMMMMM===============sssdssds#',
      '#dssdMMMMMMMMMMM===============ssssssss#',
      '#sdssMMMMMMMMMMMssdsssdssssdsssssssdsss#',
      '#ssssMMMMMMMMMMMssssssssssssdsssdssssss#',
      '#ssssMMMMMMMMMMMsssdddsssssss~~~~~sssss#',
      '#ssssssssssssssssssssssdssss~~~~~~~ssss#',
      '#sdsssssssssssssssssssssssdsg~~~~~sddss#',
      '#####ssdssdssssssssssdssssrrgsgssssssss#',
      '#####sssssddssssdsssssssssrrgssssd######',
      '#####sssdrrrrsssssssssssgssgsssdss######',
      '#####ssssrrrrssssssssssssgggsgsssd######',
      '#####sssdssdsssssssssssssgdggggsss######',
      '#####ssssdsssdsdsssssssdsggsgsdsss######',
      '########################################',
      '########################################',
    ],
    props: [
      ['spaceship', 5.6, 10.6], { kind: 'c08_truck', x: 23, y: 16, flag: 'chapter==8' }, ['hut', 31, 6.4], ['well', 28, 9.6],
      ['c08_mushroom', 6, 2.4], ['c08_mushroom', 25, 2.4], ['c08_mushroom', 35, 11.6], ['c08_mushroomBlue', 13, 19.4],
      ['c08_mushroomBlue', 6.4, 20.6], ['c08_mushroom', 28.6, 20.4], ['c08_mushroomBlue', 36.6, 17.6], ['c08_mushroomBlue', 11, 4.6],
      ['boulder', 9.4, 22], ['smallRock', 18, 22], ['rock', 2, 16.6], ['rock', 37, 7.4], ['crater', 15, 24.4], ['grassTuft', 26, 23],
      ['crate', 21.4, 17], ['crate', 21.4, 18.1],
    ],
    npcs: [
      { id: 'c08_l_jaco', sprite: 'jaco', x: 16, y: 12, dir: 'down', talk: 'c08_jaco_talk', name: 'Jaco', showIf: 'chapter==8&c08_landed' },
      { id: 'c08_l_patrol', sprite: 'c08_patrolman', x: 13, y: 18, dir: 'right', talk: 'c08_patrol_talk', name: 'Patrolman', showIf: 'chapter>=8&c08_landed', wander: 1 },
      // Monaka was off delivering when Jaco's ship landed; he is back at his truck once the boys are safe.
      { id: 'c08_l_monaka', sprite: 'monaka', x: 26, y: 18, dir: 'left', talk: 'c08_monaka_talk', name: 'Monaka', showIf: 'chapter==8&c08_boysFound' },
      { id: 'c08_l_potage', sprite: 'c08_potage', x: 30, y: 10, dir: 'down', talk: 'c08_potage_talk', name: 'Potage', showIf: 'chapter>=8&c08_boysFound' },
      { id: 'c08_l_goten', sprite: 'goten', x: 18, y: 9, dir: 'down', talk: 'c08_boys_talk', name: 'Goten', showIf: 'chapter==8&c08_boysFound&!c08_done', wander: 1 },
      { id: 'c08_l_trunks', sprite: 'trunksKid', x: 22, y: 9, dir: 'down', talk: 'c08_boys_talk', name: 'Trunks', showIf: 'chapter==8&c08_boysFound&!c08_done', wander: 1 },
    ],
    pickups: [{ id: 'c08_parcel1', item: 'c08_parcel', x: 32, y: 24, showIf: 'quest:c08_delivery' }],
    objects: [
      { type: 'save', x: 17, y: 11 },
      { type: 'worldSign', x: 16, y: 16 },
      { type: 'sign', x: 24, y: 7, text: 'POTAUFEU. Population: 1. Please do not open anything that looks sealed.' },
    ],
    exits: { north: { to: 'c08_potaufeu_mushrooms' } },
  },
  {
    id: 'c08_potaufeu_mushrooms', name: 'Mushroom Forest', music: 'alien', hostile: true, region: 'Potaufeu',
    legend: { '#': 'cliff', s: 'sand', d: 'dirt', g: 'alienGrass', u: 'ruins', '~': 'water' },
    grid: [
      '############################################',
      '############################################',
      '#########ssgggdguuuuuuuuuuuuggsggg##########',
      '#########sggggssuuuuuuuuuuuugggggs####ssss##',
      '#########gsgggdsuuuuuuuuuuuugggggg####ssss##',
      '#########ggggsgguuuuuuuuuuuudggggg####ssss##',
      '#########ggdgsgguuuuuuuuuuuugggggg##ssssss##',
      '#gssgdggsggggggggggddddddgggggggggdgssssssg#',
      '#gssggggggggsgggsgdddddddgggdsggggdgggggggg#',
      '#ggggggg##########gddddddg##########gggggdg#',
      '#gggsggg##########gddddddg##########ggggggg#',
      '#gdsgsdg##gsgggggggddddddgggsggggg##sgdddds#',
      '#ggddddd##ggsdsgsgdddddddggsgggdgg##ggdddds#',
      '#gggsssd##ggssgsgggddddddsgsggggdg##dgddddg#',
      '#ggsssss##gsgggggggddddddsgggsggdd##ggddddg#',
      '#gsssssss#gggg###gdddddddgd###dggg##sgddddg#',
      '#sgsssss##gggg###ggddddddgg###gggs##ggddddg#',
      '#gggsssdgggggg###ggddddddgg###gggg##ggddddg#',
      '#gdgddddddddddddddddddddddddddddddddddddddg#',
      '#ggddddddddddddddddddddddddddddddddddddgggg#',
      '#gggddddddddddddddddddddddddddddddddddddsgg#',
      '####ddddggggsg###ssddddddsg###ggdgggggggggg#',
      '#######gdggggggggggddddddgggggsggsgdg#######',
      '#sggggggggdggggggggddddddggsggdsggggg#######',
      '#g~~~~~ggdggggdggggddddddggggggggggggggggsg#',
      '#g~~~~~sgggggsgdgggddddddgggsggggggssgggggd#',
      '##########ggsggggggddddddgggggggg#####~~~~##',
      '##########gggsggggdddddddggggggsg#####~~~~##',
      '##########dgggsggggddddddggggggsg###########',
      '##########gsggdgggdddddggggsggggg###########',
      '##################ddddd#####################',
      '##################ddddd#####################',
    ],
    props: [
      ['c08_vaultDoor', 20, 0], ['c08_glyphPillar', 16, 2], ['c08_glyphPillar', 27, 2],
      ['c08_mushroom', 10, 2.6], ['c08_mushroom', 29.6, 2.4], ['c08_mushroom', 1.6, 7.2], ['c08_mushroomBlue', 11.6, 11.2],
      ['c08_mushroom', 28.6, 11], ['c08_mushroomBlue', 39, 8.4], ['c08_mushroom', 10, 22.4], ['c08_mushroom', 30, 21.6],
      ['c08_mushroomBlue', 15, 22.6], ['c08_mushroomBlue', 26.6, 26], ['c08_mushroom', 37.6, 20.4], ['c08_mushroomBlue', 2.6, 18.6],
      ['c08_mushroom', 11.4, 26.6], ['c08_mushroomBlue', 33, 15], ['c08_mushroomBlue', 21.6, 14.4],
      ['rubble', 17.4, 5.6], ['rubble', 25.4, 5.6], ['boulder', 4.6, 9.6], ['smallRock', 31, 7.4], ['crater', 22, 23.4],
      ['tent', 3.4, 12.6], ['campfire', 7.4, 13.4], ['crate', 2, 16.4],
    ],
    enemies: [
      { type: 'c08_gooHench', x: 12, y: 8 }, { type: 'c08_gooHench', x: 32, y: 12 }, { type: 'c08_gooHench', x: 23, y: 19 },
      { type: 'c08_sporeBeetle', x: 6, y: 19 }, { type: 'c08_sporeBeetle', x: 38, y: 15 }, { type: 'c08_sporeBeetle', x: 28, y: 24 },
      { type: 'c08_gooBlob', x: 16, y: 25 }, { type: 'c08_gooBlob', x: 33, y: 8 },
      { type: 'c08_stalkSerpent', x: 13, y: 14 }, { type: 'c08_sporeBeetle', x: 40, y: 12 },
    ],
    triggers: [
      { id: 'c08_boysT', x: 2, y: 12, w: 6, h: 6, script: 'c08_boys', showIf: 'chapter==8&c08_landed&!c08_boysFound' },
      { id: 'c08_gryllT', x: 15, y: 6, w: 14, h: 1, script: 'c08_gryll', showIf: 'chapter==8&c08_boysFound&!c08_gryllDone' },
    ],
    warps: [{ x: 21, y: 2, w: 2, h: 1, to: 'c08_potaufeu_vault', tx: 12.5, ty: 15, dir: 'up', showIf: 'c08_gryllDone', lockedScript: 'c08_vault_locked' }],
    barriers: [{ id: 'c08_v30', x: 38, y: 6, w: 4, h: 1, level: 30, character: 'vegeta' }],
    pickups: [
      { id: 'c08_parcel2', item: 'c08_parcel', x: 2, y: 23, showIf: 'quest:c08_delivery' },
      { id: 'c08_parcel3', item: 'c08_parcel', x: 41, y: 25, hidden: true, showIf: 'quest:c08_delivery' },
    ],
    objects: [
      { type: 'save', x: 18, y: 5 },
      { type: 'chest', x: 40, y: 3, id: 'c08_nookChest', item: 'str3' },
      ...C08_JARS.map((j) => ({ type: 'breakable' as const, x: j.x, y: j.y, size: 2 as const, look: 'jar' as const, item: 'c08_water', id: j.id })),
      { type: 'breakable', x: 24, y: 13, size: 2 }, { type: 'breakable', x: 12, y: 19, size: 1 },
      { type: 'breakable', x: 17, y: 26, size: 2, look: 'crate' }, { type: 'breakable', x: 41, y: 18, size: 3, item: 'pow1', id: 'c08_rock1' },
    ],
    exits: { south: { to: 'c08_potaufeu_landing' } },
  },
  {
    id: 'c08_potaufeu_vault', name: 'Commeson Vault', music: 'tense', hostile: true, indoor: true, region: 'Potaufeu',
    tint: 'rgba(60,20,90,0.22)',
    legend: { W: 'wall', u: 'ruins', M: 'metal' },
    grid: [
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWWWWWWWWWWWWWW',
      'WMMMMMMMMMMMMMMMMMMMMMMMMW',
      'WuuuuuuuMMMMMMMMMMuuuuuuuW',
      'WuuuuuuuMMMMMMMMMMuuuuuuuW',
      'WuuuuuuuMMMMMMMMMMuuuuuuuW',
      'WuuuuuuuMMMMMMMMMMuuuuuuuW',
      'WuuuuuuuuuuuuuuuuuuuuuuuuW',
      'WuuuuuuuuuuuuuuuuuuuuuuuuW',
      'WWWWuuuuuuuuuuuuuuuuuuWWWW',
      'WWWWuuuuuuuuuuuuuuuuuuWWWW',
      'WWWWuuuuuuuuuuuuuuuuuuWWWW',
      'WWWWuuuuuuuuuuuuuuuuuuWWWW',
      'WWWWuuuuuuuuuuuuuuuuuuWWWW',
      'WWWWuuuuuuuuuuuuuuuuuuWWWW',
      'WuuuuuuuuuuuuuuuuuuuuuuuuW',
      'WWWWWWWWWWWuuuuWWWWWWWWWWW',
    ],
    props: [
      { kind: 'c08_seal', x: 10.5, y: 2.6, hideFlag: 'c08_sealOpen' }, { kind: 'c08_sealBroken', x: 10.5, y: 2.6, flag: 'c08_sealOpen' },
      ['c08_glyphPillar', 3, 3.4], ['c08_glyphPillar', 22, 3.4], ['pillar', 5.5, 6.6], ['pillar', 19.5, 6.6],
      ['brokenPillar', 5, 12], ['brokenPillar', 20, 12], ['rubble', 8.4, 14.4], ['rubble', 15.4, 14.6], ['jar', 2, 8.4], ['jar', 23, 8.4],
    ],
    triggers: [
      { id: 'c08_vaultT', x: 4, y: 11, w: 18, h: 2, script: 'c08_vault', showIf: 'chapter==8&c08_gryllDone&!c08_copyDone' },
      // Glyph pillars: light both during the Copy Vegeta fight to pin the Commeson core in place.
      { id: 'c08_glyphWT', x: 3, y: 5, w: 1, h: 2, script: 'c08_glyph_w', onAction: true, showIf: 'c08_coreHunt&!c08_glyphW' },
      { id: 'c08_glyphET', x: 22, y: 5, w: 1, h: 2, script: 'c08_glyph_e', onAction: true, showIf: 'c08_coreHunt&!c08_glyphE' },
    ],
    warps: [{ x: 11, y: 17, w: 4, h: 1, to: 'c08_potaufeu_mushrooms', tx: 21.5, ty: 4, dir: 'down' }],
    objects: [
      { type: 'breakable', x: 2, y: 4, size: 1, look: 'jar' }, { type: 'breakable', x: 23, y: 4, size: 1, look: 'jar' },
      { type: 'breakable', x: 2, y: 16, size: 2 }, { type: 'breakable', x: 23, y: 16, size: 2 },
    ],
  },
]);
