// ASCII terrain grids for world/earthB maps (one char per 16px tile). Legends live with each map
// definition in westcity.ts / wasteland.ts / desert.ts / snow.ts. Keep every row the same length.

/** Terrain grids keyed by map id. */
export const GRIDS: Record<string, string[]> = {
  wc_streets: [
    '##################taaat,,,,..........,~~~~~#', // 0
    '##################taaat,,,,..........~~~~~~#', // 1
    'tttttttttttttttttttaaat.....========.~~~~~~#', // 2
    'tttttttttttttttttttaaat.....========.~~~~~~#', // 3
    'aaaaaaaaaaaaaaaaaaaaaat.....========..~~~~~#', // 4
    'aaaaaaaaaaaaaaaaaaaaaat================~~~.#', // 5
    't#########t######ttaaat=============.......#', // 6
    't#########t######ttaaat.....========.......#', // 7
    'tttttttttttttttttttaaat........==..........#', // 8
    'tttttttttttttttttttaaat........==..........#', // 9
    'tttttttttttttttttttaaatttttttttttttttttttttt', // 10
    'tttttttttttttttttttaaatttttttttttttttttttttt', // 11
    'aaaaaaaaaaamaaaaaaaaaaaaaaaaaaamaaaaaaaaaaaa', // 12
    'aaaaaaaaaaamaaaaaaaaaaaaaaaaaaamaaaaaaaaaaaa', // 13
    'aaaaaaaaaaamaaaaaaaaaaaaaaaaaaamaaaaaaaaaaaa', // 14
    'mmmmmmtttttttttttttttttttttttttttttttttttttt', // 15
    'mmmmmmtttttttttttttttttttttttttttttttttttttt', // 16
    'mmmmmm.....f.....ff....###......aataataataa#', // 17
    'mmmmmmtttttftttttfftttt###ttttttaataataataa#', // 18
    'mmmmmmtttttftttttfftttttttttttttaaaaaaaaaaa#', // 19
    'mmmmmmtttttftttttfftttttttttttttaaaaaaaaaaa#', // 20
    'mmmmmmffffffffffffffffffffffffffaaaaaaaaaaa#', // 21
    'mmmmmmffffffffffffffffffffffffffaaaaaaaaaaa#', // 22
    'mmmmmmffffffffffffffffffffffffffaaaaaaaaaaa#', // 23
    '......f..........,,,,,,,,,....ff...........#', // 24
    '......f..........,,,...,,,....ff...........#', // 25
    '......f..........,,,...,,,....ff...........#', // 26
    '......f..........,,,,,,,,,....ff...........#', // 27
    'fffffffffffffffffffffffffffffffffffffffffff#', // 28
    'fffffffffffffffffffffffffffffffffffffffffff#', // 29
  ],
  wc_shops: [
    '####################', // 0
    '####################', // 1
    '#fffffffff#wwwwwwww#', // 2
    '#fffffffff#wwwwwwww#', // 3
    '#fffffffff#wwwwwwww#', // 4
    '#ttttttttt#wwwwwwww#', // 5
    '#ttttttttt#wwwwwwww#', // 6
    '#ttttttttttwwwwwwww#', // 7
    '#ttttttttttwwwwwwww#', // 8
    '#ttttttttt#wwwwwwww#', // 9
    '#ttttttttt#wwwwwwww#', // 10
    '#####t#########w####', // 11
  ],
  cc_yard: [
    '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,', // 0
    '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,', // 1
    '#ttttttttttt..................xxxxxxxxxxxxx.', // 2
    '#tt~~~~~~~tt..................xxxxxxxxxxxxx.', // 3
    '#tt~~~~~~~tt..................xxxxxxxxxxxxx.', // 4
    '#tt~~~~~~~tt..................xxxxxxxxxxxxx.', // 5
    '#tt~~~~~~~tt..................xxxxxxxxxxxxx.', // 6
    '#ttttttttttt..................xxxxxxxxxxxxx.', // 7
    '#ttttttttttt.mmmmmmmmmmmmmmmm.xxxxxxxxxxxxx.', // 8
    '#............mmmmmmmmmmmmmmmmxxxxxxxxxxxxxx.', // 9
    'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmxxxxxxxxxxxxxx.', // 10
    'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmxxxxxxxxxxxxxx.', // 11
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', // 12
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', // 13
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', // 14
    ',,,,,,..................................,=,,', // 15
    ',,,,,,..................................,=,,', // 16
    '#,====..................................,=,,', // 17
    '#,=,,,..................................,=,,', // 18
    '#,=,,,..................................,=,,', // 19
    '#,=,,,..................................,=,,', // 20
    '#,=,,,..................................,=,,', // 21
    '#,=,,,..................................,=,,', // 22
    '#,=,,,..................................,=,,', // 23
    '#,=,,,..................................,=,,', // 24
    '#,=,,,..................................,=,,', // 25
    '#,=,,,..................................,=,,', // 26
    '#,=,,,..................................,=,,', // 27
    '#===========================================', // 28
    '#===========================================', // 29
    '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,', // 30
    '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,', // 31
  ],
  cc_inside: [
    '####################', // 0
    '####x###############', // 1
    '#xxxxxxxxx#tttttttt#', // 2
    '#xxxxxxxxx#tttttttt#', // 3
    '#xxxxxxxxx#tttttttt#', // 4
    '#xxxxxxxxx#tttttttt#', // 5
    '#xxxxxxxxx#tttttttt#', // 6
    '#######c####c#######', // 7
    '#fffff#cccccc#wwwww#', // 8
    '#fffff#cccccc#wwwww#', // 9
    '#ffffffccccccwwwwww#', // 10
    '#fffff#cccccc#wwwww#', // 11
    '#fffff#cccccc#wwwww#', // 12
    '#########cc#########', // 13
  ],
  cc_gravity: [
    '################', // 0
    '################', // 1
    '####xxxxxxxx####', // 2
    '###xxxxxxxxxx###', // 3
    '##xxxxxxxxxxxx##', // 4
    '##xxxxxxxxxxxx##', // 5
    '##xxxxxxxxxxxx##', // 6
    '##xxxxxxxxxxxx##', // 7
    '###xxxxxxxxxx###', // 8
    '####xxxxxxxx####', // 9
    '#######xx#######', // 10
    '#######xx#######', // 11
  ],
  waste_entry: [
    '########################################', // 0
    '########################################', // 1
    '###ww####w##############################', // 2
    '###wwwwwwwwww##rrrrr#########ww#rrrr####', // 3
    '###wwwwwwwwwwwrrrrrrr#######w####rrrr###', // 4
    '###wwwwwwwwwwrrrrrrrrrwwwwww#####rrrrr##', // 5
    '###wwwwwwwwwwrrrrrrrrrwwwwwww#####rrrr##', // 6
    '###wwwwwwwww#####rrrrwwwwwwww####rrrrr##', // 7
    '###wwwwwwwww#####rrrwwwwwwwwwwwrrrrrr###', // 8
    '###wwwwwwwww#####wwwwwwwwwwwwwwwrrrrww##', // 9
    '##wwwwwwwwww#####wwwwwwwwwwwwwwwwwwwww##', // 10
    '##wwwwwwwwwww###wwwwwwwwwwwwwwwwwwwwwwww', // 11
    '#dddddddddwwwwwwdddddddddddddwwwddddwddd', // 12
    '#ddddddddddddddddddddddddddddddwdddddddd', // 13
    '#ddddddddddddddddddddddddddddddddddddddd', // 14
    '#dddddddddddddddddddwwwwwddddddddddddddd', // 15
    '#ddddddddddddddwwdddwwwwwwwdddddddwwwwww', // 16
    '#dddddddwwwwwwwwwwddwwwwwwwrrrrwwwwwwwww', // 17
    '##wwwwwwwwwwwwwwwwdddww#wrrrrrrrrwwwww##', // 18
    '###wwwwwwwwwwwwwwwwddww######rrrrrwwww##', // 19
    '###wrrrrwwwwwwwwwwwddw########rrrrwwww##', // 20
    '###rrrrr#wwwwwwwwwwddww######rrrrrwwww##', // 21
    '##rrrrrr###wwwwwwwdddww######rrrrrwwww##', // 22
    '##rrrrrr###wwwwwwwdddwwwwrr##rrrrwwwww##', // 23
    '##wrrrrr#wwwwwwwwwdddwwwwwwrrrrwwwwwww##', // 24
    '##wwrrrrwwwwwwwwwwdddwwwwwwwwwwwwwwwww##', // 25
    '#wwwwwwwwwwwwww###ddd########w##########', // 26
    '######wwww##w###########################', // 27
    '########################################', // 28
    '########################################', // 29
  ],
  waste_canyon: [
    '##############################dddddd########', // 0
    '############################dddddddd########', // 1
    '###rrrrrrr#####dddddddd##dddddddddd#########', // 2
    '###rrrrrrrdd##dddddddddddddddddddd##########', // 3
    '###rrrrrrrddddddddddddddddddddddd###########', // 4
    '###rrrrrrrdddddddddddddddrrrdddd############', // 5
    '###rrrrrrr##dddddddddddddrrrdddd############', // 6
    '###########dddddd########rrr################', // 7
    '###########dddddd######rrrrr################', // 8
    '###########dddddd######rrrrr################', // 9
    '##########rdddddd##rrrrrrrrr################', // 10
    'dddddd#dddrdddddr#rrrrrrrrrr################', // 11
    'dddddddddrrddddrrrrrrrrrrr##################', // 12
    'dddddddddrrrrrrrrrrrrrrrr###################', // 13
    'dddddddddrrrrrrrrrrr########################', // 14
    'dddddddddrrrrrrrrr##########################', // 15
    'dddddddddrrrdddddr###################rrr####', // 16
    'dddddd####rrddddd##################rrrrrrr##', // 17
    '##########rrdddddd#################wwwwwwr##', // 18
    '############dddddd####wwwww#######rwwwwwwrr#', // 19
    '############ddddddddwwwwwwwww#####rwwwwwwrr#', // 20
    '##############dddddwwwwwwwwwwww###rwwwwwwrr#', // 21
    '##############ddddwwwwwwwwwwwww###rwwwwwwrr#', // 22
    '###############dddwwwwwwwwwwwww###rwwwwwwrr#', // 23
    '###############dddwwwwwwwwwwwww####wwwwwwr##', // 24
    '###################wwwwwwwwwww#####rrrrrrr##', // 25
    '####################wwwwwwwww########rrr####', // 26
    '######################wwwww#################', // 27
    '############################################', // 28
    '############################################', // 29
  ],
  waste_mesa: [
    '################################################', // 0
    '################################################', // 1
    '###rrrrrrrr##w####wwwww#########################', // 2
    '###rrrrrrrr##wwwwwwwwwwwww###wwwwwww##ddddddd###', // 3
    '###rrrrrrrr##wwwwwwwwwwwwwwwwwwwwwww##ddddddd###', // 4
    '###rrrrrrrr##wwwwwwwwwwwwwwwwwwwwwww##ddddddd###', // 5
    '###rrrrrrrr##wwwwwwwwwwwwwwwwwwwwwww##ddddddd###', // 6
    '###rrrrrrrr##wwwwwwwwwwwwwwwwwwwwwww##ddddddd###', // 7
    '#############wwwwwwwwwwwwwwwwwwwwwww##ddddddd###', // 8
    '#############wwwwwwwwwwwwwwwwwwddddd####ddd#####', // 9
    '#############wwwwrrrrrrwwwwwwwdddddd####ddd#####', // 10
    '###wwwwwwwwwwwwrrrrrrrrrrwwwwwdddddddwwwwwwwww##', // 11
    '##wwwwwwwwwwwwrrrrrrrrrrrrwwwwdddddddwwwwwwww###', // 12
    '##wwwwwwwwwwwwrrrrrrrrrrrrwwwwwdddddwwwwwwwww###', // 13
    '#######wwwwwwwrrrrrrrrrrrrwwwwwwwwwwwwwwwwwww###', // 14
    '########wwwwwwrrrrrrrrrrrrwwwwwwwwwwwwwwwwwww###', // 15
    '#######wwwwwwwwrrrrrrrrrrwwwwwwwwwwwwwwwwwww####', // 16
    '#######wwwwwwwwwwrrrrrrwwwwwwwwwwwwwwwwwwwww####', // 17
    '#####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###', // 18
    '####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###', // 19
    '####wwwwwwwwwwwwwwwwwwwwwwwwwwwrrrrrrwwwwwwwww##', // 20
    '####wwwwwwwwwwwddddwwwwwwwwwwrrrrrrrrrrwwwwwww##', // 21
    '####wwwwwwwwwwddddddwwwwwwwwrrrrrrrrrr#r#wwwww##', // 22
    '###wwww#w##wwddddddddwwwwwwwrrrrrrrrr#####www###', // 23
    '###wwww#####wddddddddwwwwwwwrrrrrrrrr#####ww####', // 24
    '###www######wwddddddwddddwwwrrrrrrrrrr####www###', // 25
    '##wwwww#####wwwddddwwddddwwwwrrrrrrrrr#w#www####', // 26
    '##wwwww#wwwwwwwwwwwwwddddwwwwwwrrrrrrwwwwwww####', // 27
    '##wwwwwwwwwwwwwwwwwwddddddwwwwwwwwwwwwwwwwww####', // 28
    '##wwwwwwwwwwwwwwwwwwddddddwwwwwwwwwwwwwwwwwww###', // 29
    '#############w#####wddddddw#wwwwwwwwwwwwwwww####', // 30
    '####################dddddd####wwwwwwwww#www#####', // 31
    '####################dddddd######################', // 32
    '####################dddddd######################', // 33
  ],
  desert_entry: [
    '##########################################', // 0
    '#ssss###########################sssssss###', // 1
    '#ssssss##sss##s#####sss#s######sssssssss##', // 2
    '#ssssssssss####wssssssssssss##sssss#sssss#', // 3
    '##sssssssww#####wwsssssssswwwwwws####ssss#', // 4
    '#ssssssssww#####wwsssssswwwwwwwwww###ssss#', // 5
    '#ssssssssss#####sssssssswwwwwwwwwwsssssss#', // 6
    '#ssssssssssrrrrrrssssssswwwwwwwwwwsssssss#', // 7
    '#sssssssssrrrrrrrrsssssssswwwwwwsssssssss#', // 8
    '#ssssssssssrrrrrrsssswwwwssssssssssssssss#', // 9
    '#ssssssssssssssssssswwwwwwssssssssssssssss', // 10
    '#sssssssssssssssssssswwwwsssssssssssssssss', // 11
    '#ddddddddsddddddssssssssssssssddddddddssss', // 12
    '#ddddddddddddddddddssssddddddddddddddddddd', // 13
    '#ddddddddddddddddddddddddddddddddddddddddd', // 14
    '#dddddddddddsssssdddddddddssdddssssssdddds', // 15
    '#ddddddddssssssssddsssssssssssssssssssssss', // 16
    '#ddddddddssssssssddsssssssssssssssssssssss', // 17
    '##sssssssssssssssdddsssssss#ssssssssssssss', // 18
    '##ssssssssssssssuddduussss#####ssssssssss#', // 19
    '#ssssssssssssssuuddduuussss####ssssssssss#', // 20
    '#ssssswwwwwsssuuuuuuuuuusss####sssssssss##', // 21
    '#ssswwwwwwwwwsuuuuuuuuuussrrrrrrwwwwwsss##', // 22
    '#ssswwwwwwwwwsuuuuuuuuuusrrrrrrrrwwwwwws##', // 23
    '##sswwwwwwwwwssuuuuuuuussrrrrrrrrwwwwwws##', // 24
    '#ssssswwwwwsssssuuuuuussssrrrrrrwwwwwss###', // 25
    '#ssssssssssssssssssssssssssssssssssssss###', // 26
    '#sssssssssss##sssssssssssssssssssssssss###', // 27
    '#s######ss######sssssssssss######sss######', // 28
    '##########################################', // 29
  ],
  desert_oasis: [
    '##################ssddds##################', // 0
    '##########sssssss#ssddds##################', // 1
    '#s#sss##ssssssssssssdddss######wwwwww#####', // 2
    '##sssssssssssssssssdddsssssssswwwwwwww####', // 3
    '##sssssssssssssssssddssssssssswwwwwwwws###', // 4
    '##ssssssssssssssdddddsssssssssswwwwwwss###', // 5
    '#ssssssssssddddddddddssssssssssssssssss###', // 6
    '##sssssddddddddddddddssssssssssssssssss###', // 7
    '##ssssdddddddddddddsssssssssssddddddss####', // 8
    '##sssdddddddd...ddddddsssssssdddddddds####', // 9
    'ssssddd...~~~~....dddddsssssdddddddddd####', // 10
    'ssdddd..~~~~~~~~...ssddddssdddddddddddd###', // 11
    'sdddd..~~~~~~~~~~...ssdddddddddddddddddd##', // 12
    'ddds...~~~~~~~~~~...ssssdddddddddddddddd##', // 13
    'ddss...~~~~~~~~~~...ssssssdddddddddddddd##', // 14
    'ssss...~~~~~~~~~~...ssssssdddddddddddddd##', // 15
    'ssss....~~~~~~~~....ssssssdddddddddddddd##', // 16
    'sssss.....~~~~.....sssssssdddddddddddddd##', // 17
    'ssssss............sssssssssdddddddddddd###', // 18
    '##sssss..........sssssssssssdddddddddds###', // 19
    '##sssssss......sssssswwwwssssdddddddds####', // 20
    '##ssssssssssssssssswwwwwwwwsssddddddss####', // 21
    '##ssswwwwwwsssssssswwwwwwwwsssssssssss####', // 22
    '##swwwwwwwwwwsssssswwwwwwwwsssssssssss####', // 23
    '##swwwwwwwwwwsssssssswwwwsssssssssssss####', // 24
    '##ssswwwwwwssssssssssssssssssssssssssss###', // 25
    '##sssssssssssssssssssssssssssssssssssss###', // 26
    '##sssssssssssssssssssssssssssssssssssss###', // 27
    '##ssss#ssssssssss#ss##ssssss#ss##sssss####', // 28
    '##########################################', // 29
  ],
  pilaf_castle_out: [
    '########################################', // 0
    '############ssss###sss#sss##ss####ssss##', // 1
    '########sWWWWWWWWWWWWWWWWWWWWWWssssss###', // 2
    '###ssssssWtttttWWWWWWWWWWtttttWssssss###', // 3
    '###swwsssWtttttWWWWWWWWWWtttttWssssss###', // 4
    '##swwwwssWtttttWWWWWWWWWWtttttWssswww###', // 5
    '##wwwwwwsWtttttWWWWWWWWWWtttttWssswww###', // 6
    '##wwwwwwsWttttttttttttttttttttWsswwwww##', // 7
    '##wwwwwwsWttttttttttttttttttttWsswwwww##', // 8
    '##wwwwwwsWttttttttttttttttttttWsswwwww##', // 9
    '#swwwwwwsWttttttttttttttttttttWsswwwww##', // 10
    '#swwwwwwsWttttttttttttttttttttWsswwwww##', // 11
    '##swwwwssWttttttttttttttttttttWsswwwww##', // 12
    '#ssswwsssWttttttttttttttttttttWssswww###', // 13
    '##sssssssWttttttttttttttttttttWssswwws##', // 14
    '##sssssssWttttttttttttttttttttWssssssss#', // 15
    '##sssssssWttttttttttttttttttttWsssssss##', // 16
    '#ssssssssWttttttttttttttttttttWsssssss##', // 17
    '#ssssssssWttttttttttttttttttttWsssssss##', // 18
    '#ssssssssWWWWWWWWWttttWWWWWWWWWsssssss##', // 19
    '#ssswwwwwwsssssssddddsssssssssssssssss##', // 20
    '##swwwwwwwwssssssdddddssssssssswwww#ss##', // 21
    '##w#w#wwwwwwsssssdddddsssssssswwww######', // 22
    '######wwwwwwssssssddddssssssswwwww######', // 23
    '######wwwwwsssssssddddssssssswwwww##ww##', // 24
    '####wwwwwwsssssssssdddsssssssswwwwwwws##', // 25
    '###ssssssssssssssssdddssssssssswwwwwss##', // 26
    '###ssssssssssssssssdddssssssssssssssss##', // 27
    '###ssssssss##ssssssdddssssssss####sss###', // 28
    '##################sdddss################', // 29
  ],
  pilaf_castle_in: [
    '################################', // 0
    '################################', // 1
    '#ttttttt##cccccccccccc##fffffff#', // 2
    '#ttttttt##cccccccccccc##fffffff#', // 3
    '#ttttttt##cccccccccccc##fffffff#', // 4
    '#ttttttt##cccccccccccc##fffffff#', // 5
    '###tt#####cccccccccccc#####tt###', // 6
    '###tt##########tt##########tt###', // 7
    '###tt##########tt##########tt###', // 8
    '###tt##########tt##########tt###', // 9
    '###tt##########tt##########tt###', // 10
    '#xxxxxxx#######tt#######fffffff#', // 11
    '#xxxxxxx#######tt#######fffffff#', // 12
    '#xxxxxxx###tttttttttt###fffffff#', // 13
    '#xxxxxxx###tttttttttt###fffffff#', // 14
    '#xxxxxxxttttttttttttttttfffffff#', // 15
    '#xxxxxxxttttttttttttttttfffffff#', // 16
    '#xxxxxxx###tttttttttt###fffffff#', // 17
    '#xxxxxxx###tttttttttt###fffffff#', // 18
    '#xxxxxxx###tttttttttt###fffffff#', // 19
    '###############tt###############', // 20
    '###############tt###############', // 21
  ],
  snow_entry: [
    '##################nnrrrnn#################', // 0
    '##################nrrrrnn#################', // 1
    '###nn#############nrrrrnn#################', // 2
    '###nnnnnnnnnnn###nnrrrrnn####n###nnnnnnn##', // 3
    '###nnnnnnnnnnnnnnnnrrrrnnnnnnnn##nnnnnnn##', // 4
    '###nnnnnnnnnnnnnnnnrrrrnnnnnnnn##nnnnnnn##', // 5
    '##nnnnnnnnnnnnnnnnnrrrrnnnnnnnn##nnnnnnn##', // 6
    '##nnnnniiiiinnnnnnnrrrrrnnnnnnn##nnnnnnn##', // 7
    '##nnniiiiiiiiinnnnnnrrrrnnnnnnn###########', // 8
    '##nniiDDDiiiiiinnnnnrrrrnnnnnnn###########', // 9
    '##niiiDDDiiiiiiinnnnrrrrnnnnnnnnnnnnnnnn##', // 10
    '##niiiiiiiiiiiiinnnrrrrrnnnnnnnnnnnnnnnn##', // 11
    '##niiiiiiiiiiiiinnnrrrrrnnnnnnnnnnnnnnnn##', // 12
    '###iiiiiiiiDDiiinnnrrrrrnnnnnnnnnnnnnnnnn#', // 13
    '##niiiiiiiiDDirrrnrrrrrnnnnnnnnnnnnnnnnnn#', // 14
    '###niiiiiiiiiirrrrrrrrrnnnn###nnnnnnnnnn##', // 15
    '###nniiiiiiiiinnrrrrrrrnnnn###nnnnnnnnnn##', // 16
    '###nnnniiiiinnnnnnrrrrnnnnn####nnnnnnnnn##', // 17
    '###nnnnnnnnnnnnnnnnrrrnnnnnn#nnnnnnnnnnn##', // 18
    '###nnnnnnnnnnnnnnnnrrrrnnnnnnnnnnnnnnnn###', // 19
    '###nnnnnn#nnnnnnnnnrrrrnnnnnnnnnnnnnnnn###', // 20
    '###nnnnnn#####nnnnnrrrrnnnnnnnnnnnnnnnnn##', // 21
    '###nnnnn#####nnnrrrrrrrrrrnnnnnnnnnnnnnn##', // 22
    '###nnnnnn####nnnrrrrrrrrrrnnnnnnnnnnnnnn##', // 23
    '###nnnnnnnnnnnnnrrrrrrrrrrnnnnnnnnnnnnn###', // 24
    '##nnnnnnnnnnnnnnrrrrrrrrrrnnnnnnnnnnnnnn##', // 25
    '#nnnnnnnnnnnnnnnrrrrrrrrrrnnnnnnnnnnnnnnn#', // 26
    '#n#######nnnnnnnrrrrrrrrrrnnnnnnnn########', // 27
    '##############nnnnnnnnnnnnnn##############', // 28
    '##########################################', // 29
  ],
  snow_peak: [
    '##############################################', // 0
    '###############rrr###rrr###rrr################', // 1
    '###############rrr###rrr###rrr################', // 2
    '###############rrrrrrrrrrrrrrrrr##############', // 3
    '##############rrrrrrrrrrrrrrrrrrr#############', // 4
    '##############rrrrrrrrrrrrrrrrrrr#############', // 5
    '##############rrrrrrrrrrrrrrrrrrr#############', // 6
    '###############rrrrrrrrrrrrrrrrr##############', // 7
    '##############################################', // 8
    '##############################################', // 9
    '##############################################', // 10
    '##############################################', // 11
    '#####,,,,,#######nnnnnnnnnnnn#################', // 12
    '####,,,,,,,#####nnniiiinnnnnnnn###############', // 13
    '###,,,...,,,###nniiiiiiiinnnnn################', // 14
    '##,,,.....,,,##nniiiiiiiinnnnn################', // 15
    '##,,.......,,##nniiiiiiiinnnnnn###############', // 16
    '##,,..~~...,,##nnnniiiinnrrrrnn###############', // 17
    '#,,..~~~~...,..nnnnnnnnnrrrrrrn###############', // 18
    '#,,...~~....,..nnnnnnnnnrrrrrr#######iiii#####', // 19
    '#,,.........,..nnnnnnrrrnrrrrn######iiiiii####', // 20
    '#,,.........,,#nnnnnnrrrrnnnnnn####iiiiiiii###', // 21
    '#,,.........,,##nnnnnrrrrrnnnnn###iiiiiiiiii##', // 22
    '#,,.........,,##nnnnnnrrrrrnnnrrrriiiiiiiiii##', // 23
    '#,,,.......,,,#nnnnnnnnrrrrnnnrrrriiiiiiiiii##', // 24
    '##,,.......,,##nnnnnnnrrrrrnnnrrrriiiiiiiiii##', // 25
    '##,,,.....,,,##nnnnrrrrrrrrnnnn###iiiiiiiiii##', // 26
    '##,,,,...,,,,###nnnrrrrrrrnnnnn###iiiiiiiiii##', // 27
    '###,,,,,,,,,####nnrrrrrrrnnnnn#####iiiiiiii###', // 28
    '####,,,,,,,####nnnrrrrrrrnnnn#######iiiiii####', // 29
    '#####,,,,,#####nnnrrrrrrrnnnnnn######iiii#####', // 30
    '###############nn#rrrrrrr#####################', // 31
    '###############n##rrrrrrr#####################', // 32
    '##################rrrrrrr#####################', // 33
  ],
};
