import { registerMaps } from '../../registry';
import { HUB } from './hubs';

/**
 * Chapter 3 maps:
 *  - c03_pilaf_vault: the security basement under Pilaf's castle (lever puzzle that opens the castle vault upstairs,
 *    Goku L14 gate in front of Pilaf's private treasure room).
 *  - c03_sky_sea: cloud banks over the southern sea where Goku (SSG) fights Beerus.
 *  - c03_orbit: Earth's orbit, for the space clash cutscene.
 */
registerMaps([
  {
    id: 'c03_pilaf_vault', name: 'Pilaf\'s Security Basement', music: 'cave', hostile: true, indoor: true, region: 'Diablo Desert',
    tint: 'rgba(30,10,50,0.18)',
    legend: { '#': 'wall', m: 'metal', c: 'carpet' },
    grid: [
      '############################',
      '############################',
      '##mmmmmmmmmmmm##cccccccccc##',
      '##mmmmmmmmmmmm##cccccccccc##',
      '##mmmmmmmmmmmm##cccccccccc##',
      '##mmmmmmmmmmmmmmcccccccccc##',
      '##mmmmmmmmmmmmmmcccccccccc##',
      '##mmmmmmmmmmmm##cccccccccc##',
      '##mmmmmmmmmmmm##cccccccccc##',
      '######mmmm######cccccccccc##',
      '######mmmm######cccccccccc##',
      '##mmmmmmmmmmmm##############',
      '##mmmmmmmmmmmm##############',
      '##mmmmmmmmmmmm##############',
      '##mmmmmmmmmmmm##############',
      '##mmmmmmmmmmmm##############',
      '##mmmmmmmmmmmm##############',
      '##mmmmmmmmmmmm##############',
      '##mmmmmmmmmmmm##############',
      '####mm######################',
    ],
    props: [
      // Lever hall: four statues against the north wall, a lever under each.
      ['c03_statueDragon', 2.75, 1], ['c03_statuePilaf', 5.75, 1], ['c03_statueMoon', 8.75, 1], ['c03_statueSun', 11.75, 1],
      { kind: 'c03_leverUp', x: 3.25, y: 3.2, id: 'c03_lvu_dragon', hideFlag: 'c03_vaultOpen' },
      { kind: 'c03_leverUp', x: 6.25, y: 3.2, id: 'c03_lvu_pilaf', hideFlag: 'c03_vaultOpen' },
      { kind: 'c03_leverUp', x: 9.25, y: 3.2, id: 'c03_lvu_moon', hideFlag: 'c03_vaultOpen' },
      { kind: 'c03_leverUp', x: 12.25, y: 3.2, id: 'c03_lvu_sun', hideFlag: 'c03_vaultOpen' },
      { kind: 'c03_leverDown', x: 3.25, y: 3.2, id: 'c03_lvd_dragon', flag: 'c03_vaultOpen' },
      { kind: 'c03_leverDown', x: 6.25, y: 3.2, id: 'c03_lvd_pilaf', flag: 'c03_vaultOpen' },
      { kind: 'c03_leverDown', x: 9.25, y: 3.2, id: 'c03_lvd_moon', flag: 'c03_vaultOpen' },
      { kind: 'c03_leverDown', x: 12.25, y: 3.2, id: 'c03_lvd_sun', flag: 'c03_vaultOpen' },
      ['lamp', 2, 7], ['lamp', 13, 7],
      // Pilaf's private treasure room (behind the Goku L14 gate).
      ['rug', 19.5, 4.5], ['c03_pedestal', 16.6, 1.6], ['c03_pedestal', 23.6, 1.6], ['throne', 19.5, 1.2],
      ['barrel', 16.2, 8], ['crate', 24.8, 7.6], ['jar', 18, 9], ['jar', 19, 9.2],
      // Entry hall clutter: the gang's "office".
      ['table', 6, 12], ['chair', 5, 12.4], ['bookshelf', 9.5, 10.5], ['tv', 2.2, 11], ['stairs', 4.5, 18], ['lamp', 2, 15], ['lamp', 13, 15],
      ['crate', 11.5, 17.4], ['barrel', 12.8, 17.6],
    ],
    enemies: [
      { type: 'pilafRobot', x: 8, y: 15 }, { type: 'pilafRobot', x: 11, y: 13 },
      { type: 'drone', x: 5, y: 7 }, { type: 'drone', x: 11, y: 6 },
      { type: 'greenDrone', x: 21, y: 7 },
    ],
    barriers: [{ id: 'c03_g14', x: 14, y: 5, w: 2, h: 2, level: 14, character: 'goku' }],
    objects: [
      { type: 'save', x: 3, y: 17 },
      { type: 'chest', x: 17, y: 4, id: 'c03_vaultChest1', item: 'str1' },
      { type: 'chest', x: 24, y: 9, id: 'c03_vaultChest2', item: 'senzu' },
      { type: 'chest', x: 22, y: 4, id: 'c03_vaultChest3', item: 'pow3' },
      { type: 'breakable', x: 3, y: 13, size: 1, look: 'crate' }, { type: 'breakable', x: 12, y: 12, size: 1, look: 'jar' },
      { type: 'breakable', x: 10, y: 17, size: 2, look: 'crate' }, { type: 'breakable', x: 2, y: 8, size: 1, look: 'jar' },
      { type: 'breakable', x: 25, y: 5, size: 1, look: 'jar' },
      { type: 'sign', x: 8, y: 8, text: 'VAULT SECURITY. Correct password = vault opens upstairs. Wrong password = robots. Lots of robots. - Mgmt.' },
    ],
    warps: [{ x: 4, y: 19, w: 2, h: 1, to: HUB.castleIn.map, tx: HUB.castleIn.x, ty: HUB.castleIn.y, dir: 'down', door: true }],
    triggers: [
      { id: 'c03_memoDesk', x: 6, y: 13, w: 2, h: 1, script: 'c03_memo', onAction: true },
      { id: 'c03_leverDragon', x: 3, y: 4, w: 1, h: 1, script: 'c03_lever_dragon', onAction: true },
      { id: 'c03_leverPilaf', x: 6, y: 4, w: 1, h: 1, script: 'c03_lever_pilaf', onAction: true },
      { id: 'c03_leverMoon', x: 9, y: 4, w: 1, h: 1, script: 'c03_lever_moon', onAction: true },
      { id: 'c03_leverSun', x: 12, y: 4, w: 1, h: 1, script: 'c03_lever_sun', onAction: true },
    ],
    onEnter: 'c03_vault_enter',
  },
  {
    id: 'c03_sky_sea', name: 'Skies over the Southern Sea', music: 'godly', hostile: true, region: 'Southern Sea', backdrop: '#3870c0',
    legend: { '~': 'deep', c: 'cloud', s: 'sand', g: 'grass' },
    grid: [
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~ccccc~~~~~~~~~~~~~~~~',
      '~~~~~~~~cccccccccccc~~~~~ccc~~~~',
      '~~~~~~ccccccccccccccccc~cccccc~~',
      '~~~~~cccccccccccccccccccccccccc~',
      '~~~~ccccccccccccccccccccccccccc~',
      '~~~cccccccccccccccccccccccccc~~~',
      '~~~ccccccccccccccccccccccccccc~~',
      '~~cccccccccccccccccccccccccccc~~',
      '~~ccccccccccccccccccccccccccccc~',
      '~~ccccccccccccccccccccccccccccc~',
      '~~cccccccccccccccccccccccccccc~~',
      '~~~ccccccccccccccccccccccccccc~~',
      '~~~~cccccccccccccccccccccccccc~~',
      '~~~~~ccccccccccccccccccccccc~~~~',
      '~~ss~~ccccccccccccccccccccc~~~~~',
      '~ssgs~~~cccccccccccccccc~~~~~~~~',
      '~sgggs~~~~~cccccccccc~~~~~~~~~~~',
      '~~sgss~~~~~~~~ccccc~~~~~~~~~~~~~',
      '~~~ss~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    ],
    props: [['palm', 1.5, 15.6], ['floatingRock', 10, 6], ['floatingRock', 21, 12.5], ['floatingRock', 25, 3.6], ['smallRock', 3, 18]],
    npcs: [{ id: 'c03_beerusNpc', sprite: 'beerus', x: 22, y: 11, dir: 'left', talk: 'c03_battle', name: 'Beerus', showIf: 'c03_ritualDone&!c03_beerusDone' }],
    triggers: [{ id: 'c03_beerusZone', x: 17, y: 3, w: 1, h: 15, script: 'c03_battle', showIf: 'c03_ritualDone&!c03_beerusDone' }],
    objects: [
      { type: 'save', x: 4, y: 9 },
      { type: 'breakable', x: 6, y: 13, size: 2 }, { type: 'breakable', x: 27, y: 9, size: 2 },
      { type: 'breakable', x: 15, y: 16, size: 2 }, { type: 'breakable', x: 13, y: 3, size: 1 },
    ],
  },
  {
    id: 'c03_orbit', name: 'Earth\'s Orbit', music: 'godly', hostile: false, region: 'Space', backdrop: '#000008',
    legend: { v: 'void', r: 'rock' },
    grid: [
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvrrrvvvvvvvvvvv',
      'vvvvvvvvvrrrrrvvvvvvvvvv',
      'vvvvvvvvvrrrrrrvvvvvvvvv',
      'vvvvvvvvvvrrrrvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
      'vvvvvvvvvvvvvvvvvvvvvvvv',
    ],
    props: [['c03_earth', 1, 8], ['floatingRock', 17, 2], ['floatingRock', 3, 2]],
  },
]);
